/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-05-31 15:21:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- ======= Header ======= -->\r\n");
      out.write("<header id=\"header\" class=\"header fixed-top d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("        <a href=\"index.jsp\" class=\"logo d-flex align-items-center\">\r\n");
      out.write("            <img src=\"assets/img/logo.png\" alt=\"\">\r\n");
      out.write("            <span class=\"d-none d-lg-block\">Aishiba</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <i class=\"bi bi-list toggle-sidebar-btn\"></i>\r\n");
      out.write("    </div><!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"search-bar\">\r\n");
      out.write("        <form class=\"search-form d-flex align-items-center\" method=\"POST\" action=\"#\">\r\n");
      out.write("            <input type=\"text\" name=\"query\" placeholder=\"Search\" title=\"Enter search keyword\">\r\n");
      out.write("            <button type=\"submit\" title=\"Search\"><i class=\"bi bi-search\"></i></button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div><!-- End Search Bar -->\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"header-nav ms-auto\">\r\n");
      out.write("        <ul class=\"d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item d-block d-lg-none\">\r\n");
      out.write("                <a class=\"nav-link nav-icon search-bar-toggle \" href=\"#\">\r\n");
      out.write("                    <i class=\"bi bi-search\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li><!-- End Search Icon-->\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("\r\n");
      out.write("                <a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                    <i class=\"bi bi-bell\"></i>\r\n");
      out.write("                    <span class=\"badge bg-primary badge-number\">4</span>\r\n");
      out.write("                </a><!-- End Notification Icon -->\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications\">\r\n");
      out.write("                    <li class=\"dropdown-header\">\r\n");
      out.write("                        You have 4 new notifications\r\n");
      out.write("                        <a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View all</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"notification-item\">\r\n");
      out.write("                        <i class=\"bi bi-exclamation-circle text-warning\"></i>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4>Lorem Ipsum</h4>\r\n");
      out.write("                            <p>Quae dolorem earum veritatis oditseno</p>\r\n");
      out.write("                            <p>30 min. ago</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"notification-item\">\r\n");
      out.write("                        <i class=\"bi bi-x-circle text-danger\"></i>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4>Atque rerum nesciunt</h4>\r\n");
      out.write("                            <p>Quae dolorem earum veritatis oditseno</p>\r\n");
      out.write("                            <p>1 hr. ago</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"notification-item\">\r\n");
      out.write("                        <i class=\"bi bi-check-circle text-success\"></i>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4>Sit rerum fuga</h4>\r\n");
      out.write("                            <p>Quae dolorem earum veritatis oditseno</p>\r\n");
      out.write("                            <p>2 hrs. ago</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"notification-item\">\r\n");
      out.write("                        <i class=\"bi bi-info-circle text-primary\"></i>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h4>Dicta reprehenderit</h4>\r\n");
      out.write("                            <p>Quae dolorem earum veritatis oditseno</p>\r\n");
      out.write("                            <p>4 hrs. ago</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"dropdown-footer\">\r\n");
      out.write("                        <a href=\"#\">Show all notifications</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                </ul><!-- End Notification Dropdown Items -->\r\n");
      out.write("\r\n");
      out.write("            </li><!-- End Notification Nav -->\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("\r\n");
      out.write("                <a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                    <i class=\"bi bi-chat-left-text\"></i>\r\n");
      out.write("                    <span class=\"badge bg-success badge-number\">3</span>\r\n");
      out.write("                </a><!-- End Messages Icon -->\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow messages\">\r\n");
      out.write("                    <li class=\"dropdown-header\">\r\n");
      out.write("                        You have 100 new messages\r\n");
      out.write("                        <a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View all</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"message-item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/img/messages-1.jpg\" alt=\"\" class=\"rounded-circle\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <h4>Maria Hudson</h4>\r\n");
      out.write("                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>\r\n");
      out.write("                                <p>4 hrs. ago</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"message-item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/img/messages-2.jpg\" alt=\"\" class=\"rounded-circle\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <h4>Anna Nelson</h4>\r\n");
      out.write("                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>\r\n");
      out.write("                                <p>6 hrs. ago</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"message-item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/img/messages-3.jpg\" alt=\"\" class=\"rounded-circle\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <h4>David Muldon</h4>\r\n");
      out.write("                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>\r\n");
      out.write("                                <p>8 hrs. ago</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"dropdown-footer\">\r\n");
      out.write("                        <a href=\"#\">Show all messages</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                </ul><!-- End Messages Dropdown Items -->\r\n");
      out.write("\r\n");
      out.write("            </li><!-- End Messages Nav -->\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item dropdown pe-3\">\r\n");
      out.write("\r\n");
      out.write("                <a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                    <img src=\"assets/img/profile-img.jpg\" alt=\"Profile\" class=\"rounded-circle\">\r\n");
      out.write("                    <span class=\"d-none d-md-block dropdown-toggle ps-2\">K. Anderson</span>\r\n");
      out.write("                </a><!-- End Profile Iamge Icon -->\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">\r\n");
      out.write("                    <li class=\"dropdown-header\">\r\n");
      out.write("                        <h6>Kevin Anderson</h6>\r\n");
      out.write("                        <span>Web Designer</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"dropdown-item d-flex align-items-center\" href=\"users-profile.html\">\r\n");
      out.write("                            <i class=\"bi bi-person\"></i>\r\n");
      out.write("                            <span>My Profile</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"dropdown-item d-flex align-items-center\" href=\"users-profile.html\">\r\n");
      out.write("                            <i class=\"bi bi-gear\"></i>\r\n");
      out.write("                            <span>Account Settings</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"dropdown-item d-flex align-items-center\" href=\"pages-faq.html\">\r\n");
      out.write("                            <i class=\"bi bi-question-circle\"></i>\r\n");
      out.write("                            <span>Need Help?</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <hr class=\"dropdown-divider\">\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("                            <i class=\"bi bi-box-arrow-right\"></i>\r\n");
      out.write("                            <span>Sign Out</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                </ul><!-- End Profile Dropdown Items -->\r\n");
      out.write("            </li><!-- End Profile Nav -->\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav><!-- End Icons Navigation -->\r\n");
      out.write("\r\n");
      out.write("</header><!-- End Header -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
