/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-05-31 15:20:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

  // Kiểm tra session
  if (session.getAttribute("username") == null) {
    response.sendRedirect("login.jsp");
  }

      out.write("\r\n");
      out.write("<main id=\"main\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"pagetitle\">\r\n");
      out.write("    <h1>Dashboard</h1>\r\n");
      out.write("    <nav>\r\n");
      out.write("      <ol class=\"breadcrumb\">\r\n");
      out.write("        <li class=\"breadcrumb-item\"><a href=\"homepage\">Trang chủ</a></li>\r\n");
      out.write("        <li class=\"breadcrumb-item active\">Dashboard</li>\r\n");
      out.write("      </ol>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </div><!-- End Page Title -->\r\n");
      out.write("\r\n");
      out.write("  <section class=\"section dashboard\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Total Revenue Card -->\r\n");
      out.write("      <div class=\"col-xxl-3 col-md-6\">\r\n");
      out.write("        <div class=\"card info-card revenue-card\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Tổng Doanh Thu <span>| Hôm nay</span></h5>\r\n");
      out.write("            <div class=\"d-flex align-items-center\">\r\n");
      out.write("              <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\"\r\n");
      out.write("                   style=\"background-color: #f0f8ff;\">\r\n");
      out.write("                <i class=\"bi bi-currency-dollar\" style=\"color: #4154f1;\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-3\">\r\n");
      out.write("                <h6>$12,099</h6>\r\n");
      out.write("                <span class=\"text-success small pt-1 fw-bold\">+0.00%</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"totalRevenueChart\" class=\"mt-2\" style=\"height: 40px;\"></div>\r\n");
      out.write("            <script>\r\n");
      out.write("              document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("                if (typeof ApexCharts !== 'undefined' && document.querySelector(\"#totalRevenueChart\")) {\r\n");
      out.write("                  new ApexCharts(document.querySelector(\"#totalRevenueChart\"), {\r\n");
      out.write("                    chart: { type: 'area', height: 40, sparkline: { enabled: true } },\r\n");
      out.write("                    stroke: { curve: 'smooth', width: 2 },\r\n");
      out.write("                    colors: ['#4154f1'],\r\n");
      out.write("                    fill: { type: 'gradient', gradient: { opacityFrom: 0.5, opacityTo: 0.2 } },\r\n");
      out.write("                    series: [{ data: [20, 70, 30, 80, 25, 75, 35, 65, 20] }],\r\n");
      out.write("                    tooltip: { enabled: false },\r\n");
      out.write("                  }).render();\r\n");
      out.write("                }\r\n");
      out.write("              });\r\n");
      out.write("            </script>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div><!-- End Total Revenue Card -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Affiliate Revenue Card -->\r\n");
      out.write("      <div class=\"col-xxl-3 col-md-6\">\r\n");
      out.write("        <div class=\"card info-card\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Doanh Thu Liên Kết <span>| Hôm nay</span></h5>\r\n");
      out.write("            <div class=\"d-flex align-items-center\">\r\n");
      out.write("              <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\"\r\n");
      out.write("                   style=\"background-color: #ffebee;\">\r\n");
      out.write("                <i class=\"bi bi-cash-coin\" style=\"color: #dc3545;\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-3\">\r\n");
      out.write("                <h6>$12,099</h6>\r\n");
      out.write("                <span class=\"text-success small pt-1 fw-bold\">+0.00%</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"affiliateRevenueChart\" class=\"mt-2\" style=\"height: 40px;\"></div>\r\n");
      out.write("            <script>\r\n");
      out.write("              document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("                if (typeof ApexCharts !== 'undefined' && document.querySelector(\"#affiliateRevenueChart\")) {\r\n");
      out.write("                  new ApexCharts(document.querySelector(\"#affiliateRevenueChart\"), {\r\n");
      out.write("                    chart: { type: 'area', height: 40, sparkline: { enabled: true } },\r\n");
      out.write("                    stroke: { curve: 'smooth', width: 2 },\r\n");
      out.write("                    colors: ['#dc3545'],\r\n");
      out.write("                    fill: { type: 'gradient', gradient: { opacityFrom: 0.5, opacityTo: 0.2 } },\r\n");
      out.write("                    series: [{ data: [30, 75, 25, 85, 30, 70, 40, 60, 25] }],\r\n");
      out.write("                    tooltip: { enabled: false },\r\n");
      out.write("                  }).render();\r\n");
      out.write("                }\r\n");
      out.write("              });\r\n");
      out.write("            </script>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div><!-- End Affiliate Revenue Card -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Refunds Card -->\r\n");
      out.write("      <div class=\"col-xxl-3 col-md-6\">\r\n");
      out.write("        <div class=\"card info-card\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\"> Tổng sản phẩm bán ra <span>| Hôm nay</span></h5>\r\n");
      out.write("            <div class=\"d-flex align-items-center\">\r\n");
      out.write("              <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\"\r\n");
      out.write("                   style=\"background-color: #e0f7fa;\">\r\n");
      out.write("                <i class=\"bi bi-box-seam\" style=\"color: #0dcaf0;\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-3\">\r\n");
      out.write("                <h6>0.00</h6>\r\n");
      out.write("                <span class=\"text-muted small pt-1\">N/A</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"refundsChart\" class=\"mt-2\" style=\"height: 40px;\"></div>\r\n");
      out.write("            <script>\r\n");
      out.write("              document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("                if (typeof ApexCharts !== 'undefined' && document.querySelector(\"#refundsChart\")) {\r\n");
      out.write("                  new ApexCharts(document.querySelector(\"#refundsChart\"), {\r\n");
      out.write("                    chart: { type: 'area', height: 40, sparkline: { enabled: true } },\r\n");
      out.write("                    stroke: { curve: 'smooth', width: 2 },\r\n");
      out.write("                    colors: ['#0dcaf0'],\r\n");
      out.write("                    fill: { type: 'gradient', gradient: { opacityFrom: 0.5, opacityTo: 0.2 } },\r\n");
      out.write("                    series: [{ data: [10, 45, 15, 50, 10, 40, 20, 35, 10] }],\r\n");
      out.write("                    tooltip: { enabled: false },\r\n");
      out.write("                  }).render();\r\n");
      out.write("                }\r\n");
      out.write("              });\r\n");
      out.write("            </script>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div><!-- End Refunds Card -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Avg. Revenue Per User Card -->\r\n");
      out.write("      <div class=\"col-xxl-3 col-md-6\">\r\n");
      out.write("        <div class=\"card info-card\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Tổng đơn hàng <span>| Hôm nay</span></h5>\r\n");
      out.write("            <div class=\"d-flex align-items-center\">\r\n");
      out.write("              <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\"\r\n");
      out.write("                   style=\"background-color: #fff8e1;\">\r\n");
      out.write("                <i class=\"bi bi-receipt\" style=\"color: #ffc107;\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"ps-3\">\r\n");
      out.write("                <h6>$28,000</h6>\r\n");
      out.write("                <span class=\"text-danger small pt-1 fw-bold\">-0.00%</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"avgRevenueUserChart\" class=\"mt-2\" style=\"height: 40px;\"></div>\r\n");
      out.write("            <script>\r\n");
      out.write("              document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("                if (typeof ApexCharts !== 'undefined' && document.querySelector(\"#avgRevenueUserChart\")) {\r\n");
      out.write("                  new ApexCharts(document.querySelector(\"#avgRevenueUserChart\"), {\r\n");
      out.write("                    chart: { type: 'area', height: 40, sparkline: { enabled: true } },\r\n");
      out.write("                    stroke: { curve: 'smooth', width: 2 },\r\n");
      out.write("                    colors: ['#ffc107'],\r\n");
      out.write("                    fill: { type: 'gradient', gradient: { opacityFrom: 0.5, opacityTo: 0.2 } },\r\n");
      out.write("                    series: [{ data: [40, 90, 30, 80, 35, 85, 45, 75, 40] }],\r\n");
      out.write("                    tooltip: { enabled: false },\r\n");
      out.write("                  }).render();\r\n");
      out.write("                }\r\n");
      out.write("              });\r\n");
      out.write("            </script>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div><!-- End Avg. Revenue Per User Card -->\r\n");
      out.write("\r\n");
      out.write("    </div> <!-- End Top Row -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row mb-4\">\r\n");
      out.write("      <div class=\"col-lg-8\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Mức độ tăng trưởng bán hàng từng năm </h5>\r\n");
      out.write("            <div id=\"customBarChart\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Tỷ lệ phần trăm sản phẩm theo danh mục</h5>\r\n");
      out.write("            <div id=\"customPieChart\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("      document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("        if (typeof ApexCharts !== 'undefined') {\r\n");
      out.write("          // Biểu đồ miền - Mức độ tăng trưởng bán hàng theo tháng so với năm trước\r\n");
      out.write("          new ApexCharts(document.querySelector(\"#customBarChart\"), {\r\n");
      out.write("            chart: { type: 'area', height: 250 },\r\n");
      out.write("            series: [\r\n");
      out.write("              { name: '2025', data: [120, 190, 170, 140, 180, 100, 220, 210, 190, 230, 290, 270] },\r\n");
      out.write("              { name: '2024', data: [100, 150, 160, 120, 160, 80, 160, 190, 170, 210, 230, 250] }\r\n");
      out.write("            ],\r\n");
      out.write("            xaxis: { categories: ['Th1', 'Th2', 'Th3', 'Th4', 'Th5', 'Th6', 'Th7', 'Th8', 'Th9', 'Th10', 'Th11', 'Th12'] },\r\n");
      out.write("            stroke: { curve: 'smooth', width: 2 },\r\n");
      out.write("            fill: { type: 'gradient', gradient: { opacityFrom: 0.5, opacityTo: 0.2 } },\r\n");
      out.write("            dataLabels: { enabled: false }\r\n");
      out.write("          }).render();\r\n");
      out.write("          // Biểu đồ tròn - Tỷ lệ phần trăm sản phẩm bán ra theo danh mục\r\n");
      out.write("          new ApexCharts(document.querySelector(\"#customPieChart\"), {\r\n");
      out.write("            chart: { type: 'pie', height: 250 },\r\n");
      out.write("            series: [40, 27, 20, 10, 3],\r\n");
      out.write("            labels: ['Đồ chơi', 'Sách', 'Quần áo', 'Đồ điện tử', 'Khác'],\r\n");
      out.write("            legend: {\r\n");
      out.write("              position: 'bottom',\r\n");
      out.write("              horizontalAlign: 'center',\r\n");
      out.write("              offsetY: 10\r\n");
      out.write("            }\r\n");
      out.write("          }).render();\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <!-- Recent Orders Table -->\r\n");
      out.write("      <div class=\"col-lg-8 d-flex\">\r\n");
      out.write("        <div class=\"card h-100 w-100\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Đơn Hàng Gần Đây <span>| Hôm nay</span></h5>\r\n");
      out.write("            <div class=\"table-responsive\" style=\"max-height: 350px; overflow-y: auto;\">\r\n");
      out.write("              <table class=\"table table-hover\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"col\">#</th>\r\n");
      out.write("                  <th scope=\"col\">Hình Ảnh</th>\r\n");
      out.write("                  <th scope=\"col\">Tên Sản Phẩm</th>\r\n");
      out.write("                  <th scope=\"col\">Số Lượng</th>\r\n");
      out.write("                  <th scope=\"col\">Giá</th>\r\n");
      out.write("                  <th scope=\"col\">Thời Gian Đặt</th>\r\n");
      out.write("                  <th scope=\"col\">Khách Hàng</th>\r\n");
      out.write("                  <th scope=\"col\">Trạng Thái</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">1</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-1.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #1</td>\r\n");
      out.write("                  <td>20</td>\r\n");
      out.write("                  <td>$60.00</td>\r\n");
      out.write("                  <td>27-08-2018 09:22:10</td>\r\n");
      out.write("                  <td>Patricia J. King</td>\r\n");
      out.write("                  <td><span class=\"badge bg-warning text-dark\">In Transit</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">2</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-2.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #2</td>\r\n");
      out.write("                  <td>12</td>\r\n");
      out.write("                  <td>$180.00</td>\r\n");
      out.write("                  <td>25-08-2018 21:12:54</td>\r\n");
      out.write("                  <td>Rachel J. Wicker</td>\r\n");
      out.write("                  <td><span class=\"badge bg-success\">Delivered</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">3</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-3.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #3</td>\r\n");
      out.write("                  <td>25</td>\r\n");
      out.write("                  <td>$200.00</td>\r\n");
      out.write("                  <td>24-08-2018 14:12:37</td>\r\n");
      out.write("                  <td>Michael K. Ledford</td>\r\n");
      out.write("                  <td><span class=\"badge bg-success\">Delivered</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">4</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-4.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #4</td>\r\n");
      out.write("                  <td>30</td>\r\n");
      out.write("                  <td>$300.00</td>\r\n");
      out.write("                  <td>23-08-2018 09:12:03</td>\r\n");
      out.write("                  <td>Michael K. Ledford</td>\r\n");
      out.write("                  <td><span class=\"badge bg-success\">Delivered</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">5</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-1.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #5</td>\r\n");
      out.write("                  <td>15</td>\r\n");
      out.write("                  <td>$120.00</td>\r\n");
      out.write("                  <td>22-08-2018 10:15:00</td>\r\n");
      out.write("                  <td>Anna Nelson</td>\r\n");
      out.write("                  <td><span class=\"badge bg-warning text-dark\">In Transit</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">6</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-2.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #6</td>\r\n");
      out.write("                  <td>10</td>\r\n");
      out.write("                  <td>$90.00</td>\r\n");
      out.write("                  <td>21-08-2018 11:30:45</td>\r\n");
      out.write("                  <td>David Muldon</td>\r\n");
      out.write("                  <td><span class=\"badge bg-success\">Delivered</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">7</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-3.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #7</td>\r\n");
      out.write("                  <td>18</td>\r\n");
      out.write("                  <td>$150.00</td>\r\n");
      out.write("                  <td>20-08-2018 13:45:20</td>\r\n");
      out.write("                  <td>Maria Hudson</td>\r\n");
      out.write("                  <td><span class=\"badge bg-warning text-dark\">In Transit</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">8</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-4.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #8</td>\r\n");
      out.write("                  <td>22</td>\r\n");
      out.write("                  <td>$210.00</td>\r\n");
      out.write("                  <td>19-08-2018 15:00:00</td>\r\n");
      out.write("                  <td>Rachel J. Wicker</td>\r\n");
      out.write("                  <td><span class=\"badge bg-success\">Delivered</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">9</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-1.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #9</td>\r\n");
      out.write("                  <td>14</td>\r\n");
      out.write("                  <td>$110.00</td>\r\n");
      out.write("                  <td>18-08-2018 16:10:10</td>\r\n");
      out.write("                  <td>Patricia J. King</td>\r\n");
      out.write("                  <td><span class=\"badge bg-warning text-dark\">In Transit</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">10</th>\r\n");
      out.write("                  <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/product-2.jpg\"\r\n");
      out.write("                           alt=\"Product Image\"\r\n");
      out.write("                           style=\"width: 40px; height: 40px; object-fit: cover;\"></td>\r\n");
      out.write("                  <td>Product #10</td>\r\n");
      out.write("                  <td>16</td>\r\n");
      out.write("                  <td>$130.00</td>\r\n");
      out.write("                  <td>17-08-2018 17:25:30</td>\r\n");
      out.write("                  <td>Michael K. Ledford</td>\r\n");
      out.write("                  <td><span class=\"badge bg-success\">Delivered</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div> <!-- End Recent Orders Table -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Customer Acquisition Chart -->\r\n");
      out.write("      <div class=\"col-lg-4 d-flex\">\r\n");
      out.write("        <div class=\"card h-100 w-100\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Thu Hút Khách Hàng <span>| Tuần Này</span></h5>\r\n");
      out.write("            <div id=\"customerAcquisitionChart\"></div>\r\n");
      out.write("            <script>\r\n");
      out.write("              document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("                if (typeof ApexCharts !== 'undefined' && document.querySelector(\"#customerAcquisitionChart\")) {\r\n");
      out.write("                  new ApexCharts(document.querySelector(\"#customerAcquisitionChart\"), {\r\n");
      out.write("                    series: [{\r\n");
      out.write("                      name: 'Quay Lại',\r\n");
      out.write("                      data: [30, 45, 60, 40, 35, 50, 70] // Placeholder\r\n");
      out.write("                    }, {\r\n");
      out.write("                      name: 'Lần Đầu',\r\n");
      out.write("                      data: [20, 25, 30, 50, 70, 80, 90] // Placeholder\r\n");
      out.write("                    }],\r\n");
      out.write("                    chart: { type: 'area', height: 365, toolbar: { show: false } },\r\n");
      out.write("                    colors: ['#4154f1', '#ff771d'], // Blue and Orange/Pink\r\n");
      out.write("                    dataLabels: { enabled: false },\r\n");
      out.write("                    stroke: { curve: 'smooth', width: 2 },\r\n");
      out.write("                    xaxis: {\r\n");
      out.write("                      categories: [\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\"],\r\n");
      out.write("                      labels: { style: { colors: '#8c909a', fontSize: '12px' } }\r\n");
      out.write("                    },\r\n");
      out.write("                    yaxis: {\r\n");
      out.write("                      min: 0,\r\n");
      out.write("                      labels: { style: { colors: '#8c909a', fontSize: '12px' } }\r\n");
      out.write("                    },\r\n");
      out.write("                    legend: {\r\n");
      out.write("                      position: 'top',\r\n");
      out.write("                      horizontalAlign: 'right',\r\n");
      out.write("                      floating: true,\r\n");
      out.write("                      offsetY: -25,\r\n");
      out.write("                      offsetX: -5,\r\n");
      out.write("                      labels: { colors: '#333' },\r\n");
      out.write("                      markers: { width: 10, height: 10 }\r\n");
      out.write("                    },\r\n");
      out.write("                    fill: {\r\n");
      out.write("                      type: \"gradient\",\r\n");
      out.write("                      gradient: {\r\n");
      out.write("                        shadeIntensity: 1,\r\n");
      out.write("                        opacityFrom: 0.6,\r\n");
      out.write("                        opacityTo: 0.2,\r\n");
      out.write("                        stops: [0, 90, 100]\r\n");
      out.write("                      }\r\n");
      out.write("                    },\r\n");
      out.write("                    tooltip: {\r\n");
      out.write("                      y: {\r\n");
      out.write("                        formatter: function (val) {\r\n");
      out.write("                          return val + \" customers\"\r\n");
      out.write("                        }\r\n");
      out.write("                      }\r\n");
      out.write("                    }\r\n");
      out.write("                  }).render();\r\n");
      out.write("                }\r\n");
      out.write("              });\r\n");
      out.write("            </script>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div> <!-- End Customer Acquisition Chart -->\r\n");
      out.write("    </div> <!-- End Second Row -->\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("</main><!-- End #main -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
