/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-05-31 03:18:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class report_005ffinance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<main id=\"main\" class=\"main\">\r\n");
      out.write("    <div class=\"pagetitle\">\r\n");
      out.write("        <h1>Báo cáo tài chính</h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Trang chủ</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Thống kê</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\">Tài chính</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <div class=\"col-lg-3 col-md-4 sidebar-main\">\r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <h5 class=\"mb-3\">Kiểu hiển thị</h5>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"displayType\" id=\"report\" checked>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"report\">Báo cáo</label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <h5 class=\"mb-3\">Thời gian</h5>\r\n");
      out.write("                <select class=\"form-select mb-3\">\r\n");
      out.write("                    <option selected>2025</option>\r\n");
      out.write("                    <option>2024</option>\r\n");
      out.write("                    <option>2023</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"time\" id=\"month\" checked>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"month\">Theo Tháng</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"time\" id=\"quarter\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"quarter\">Theo Quý</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"time\" id=\"year\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"year\">Theo Năm</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"date\" class=\"form-control mt-3\" id=\"customDateStart\">\r\n");
      out.write("                <input type=\"date\" class=\"form-control mt-2\" id=\"customDateEnd\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Content -->\r\n");
      out.write("        <div class=\"col-lg-9 col-md-8\">\r\n");
      out.write("            <div class=\"card p-4\">\r\n");
      out.write("                <div class=\"d-flex justify-content-end mb-3\" style=\"position: absolute; top: 20px; right: 20px;\">\r\n");
      out.write("                    <button class=\"btn btn-primary me-2\" id=\"printReport\">\r\n");
      out.write("                        <i class=\"bi bi-printer\"></i> In báo cáo\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"btn btn-success me-2\" id=\"exportExcel\">\r\n");
      out.write("                        <i class=\"bi bi-file-earmark-excel\"></i> Xuất Excel\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"btn btn-info\" id=\"sendEmail\">\r\n");
      out.write("                        <i class=\"bi bi-envelope\"></i> Gửi Email\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"text-muted\">Ngày lập: <strong>20/04/2025 23:10</strong></p>\r\n");
      out.write("                <h5 class=\"text-center\">Báo cáo kết quả hoạt động kinh doanh</h5>\r\n");
      out.write("                <p class=\"text-center text-muted\">Từ ngày 01/04/2025 đến ngày 20/04/2025</p>\r\n");
      out.write("                <p class=\"text-center text-muted\">Chi nhánh trung tâm</p>\r\n");
      out.write("\r\n");
      out.write("                <table class=\"table table-bordered mt-4\">\r\n");
      out.write("                    <thead class=\"table-light\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Chỉ tiêu</th>\r\n");
      out.write("                        <th class=\"text-center\">Tổng</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Doanh thu bán hàng (1)</td>\r\n");
      out.write("                        <td class=\"text-end\">298,370,000</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Giảm trừ Doanh thu (2 = 2.1+2.2)</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Chiết khấu hóa đơn (2.1)</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Giá trị hàng bán bị trả lại (2.2)</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Doanh thu thuần (3=1-2)</td>\r\n");
      out.write("                        <td class=\"text-end\">298,370,000</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Giá vốn hàng bán (4)</td>\r\n");
      out.write("                        <td class=\"text-end\">280,297,500</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Lợi nhuận gộp về bán hàng (5=3-4)</td>\r\n");
      out.write("                        <td class=\"text-end\">16,072,500</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Chi phí (6)</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Chi phí voucher</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Phí trả ĐTGH</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Xuất hủy hàng hóa</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Giá trị thanh toán bằng điểm</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Chiết khấu thanh toán cho khách</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Chi trả lương NV</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Lợi nhuận từ hoạt động kinh doanh (7=5-6)</td>\r\n");
      out.write("                        <td class=\"text-end\">16,072,500</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Thu nhập khác (8)</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Phí trả hàng</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Chiết khấu thanh toán từ NCC</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"sub-item\">Chi phí khác (9)</td>\r\n");
      out.write("                        <td class=\"text-end\">0</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Lợi nhuận thuần (10=7+8-9)</td>\r\n");
      out.write("                        <td class=\"text-end\">16,072,500</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <p class=\"text-muted text-center mt-3\">Chi nhánh trung tâm:</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("<style>\r\n");
      out.write("    /* Định vị sidebar trong main */\r\n");
      out.write("    .sidebar-main {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        /* Cố định vị trí */\r\n");
      out.write("        top: 70px;\r\n");
      out.write("        /* Khoảng cách từ trên xuống để không chèn lên header */\r\n");
      out.write("        right: 0;\r\n");
      out.write("        /* Sát cạnh phải màn hình */\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        /* Chiếm 20% chiều rộng màn hình */\r\n");
      out.write("        height: calc(100vh - 70px);\r\n");
      out.write("        /* Chiều cao toàn màn hình trừ chiều cao của header */\r\n");
      out.write("        z-index: 1020;\r\n");
      out.write("        /* Đảm bảo nằm trên các phần tử khác */\r\n");
      out.write("        overflow-y: auto;\r\n");
      out.write("        /* Cuộn dọc nếu nội dung quá dài */\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        /* Màu nền trắng */\r\n");
      out.write("        border-left: 1px solid #e0e0e0;\r\n");
      out.write("        /* Viền bên trái */\r\n");
      out.write("        box-shadow: -2px 0 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        /* Đổ bóng bên trái */\r\n");
      out.write("        padding: 16px;\r\n");
      out.write("        /* Khoảng cách bên trong */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Đảm bảo nội dung chính không bị chồng lấn */\r\n");
      out.write("    .main-content {\r\n");
      out.write("        margin-right: 20%;\r\n");
      out.write("        /* Đẩy nội dung chính sang trái để nhường chỗ cho sidebar */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Tùy chỉnh khung sidebar */\r\n");
      out.write("    .sidebar-wrapper {\r\n");
      out.write("        padding: 16px;\r\n");
      out.write("        /* Khoảng cách bên trong */\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        /* Màu nền trắng */\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        /* Bo góc */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Khung nhỏ cho từng phần */\r\n");
      out.write("    .card {\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        /* Màu nền sáng hơn */\r\n");
      out.write("        border: 1px solid #e0e0e0;\r\n");
      out.write("        /* Viền màu xám nhạt */\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        /* Bo góc nhẹ */\r\n");
      out.write("        padding: 24px;\r\n");
      out.write("        /* Tăng khoảng cách bên trong khung */\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("        /* Tăng khoảng cách giữa các khung */\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Tiêu đề của từng phần */\r\n");
      out.write("    .card h5 {\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        /* Tăng cỡ chữ tiêu đề */\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #012970;\r\n");
      out.write("        margin-bottom: 16px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Tùy chỉnh từng phần trong sidebar */\r\n");
      out.write("    .sidebar-section {\r\n");
      out.write("        margin-bottom: 16px;\r\n");
      out.write("        /* Khoảng cách giữa các phần */\r\n");
      out.write("        padding: 16px;\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        /* Nền trắng */\r\n");
      out.write("        border: 1px solid #e0e0e0;\r\n");
      out.write("        /* Viền màu xám nhạt */\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        /* Bo góc */\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        /* Đổ bóng nhẹ */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Tiêu đề của từng phần */\r\n");
      out.write("    .sidebar-section h5 {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #012970;\r\n");
      out.write("        margin-bottom: 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Input và select */\r\n");
      out.write("    .sidebar-section .form-control,\r\n");
      out.write("    .sidebar-section .form-select {\r\n");
      out.write("        margin-top: 8px;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Radio button và nhãn */\r\n");
      out.write("    .sidebar-section .form-check {\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar-section .form-check-label {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .text-center .btn {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        /* Tăng kích thước nút */\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        /* Cỡ chữ */\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        /* Bo góc nhẹ */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gap-3>* {\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("        /* Khoảng cách giữa các nút */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end .btn {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        /* Tăng kích thước nút */\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        /* Cỡ chữ */\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        /* Bo góc nhẹ */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end .btn+.btn {\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("        /* Khoảng cách giữa các nút */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end {\r\n");
      out.write("        margin-top: -10px;\r\n");
      out.write("        /* Điều chỉnh khoảng cách với tiêu đề */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 20px;\r\n");
      out.write("        /* Căn chỉnh nút cách phía trên 20px */\r\n");
      out.write("        right: 20px;\r\n");
      out.write("        /* Căn chỉnh nút cách phía phải 20px */\r\n");
      out.write("        z-index: 10;\r\n");
      out.write("        /* Đảm bảo nút nằm trên các phần tử khác */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end .btn {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        /* Tăng kích thước nút */\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        /* Cỡ chữ */\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        /* Bo góc nhẹ */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end .btn+.btn {\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("        /* Khoảng cách giữa các nút */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #chart1,\r\n");
      out.write("    #chart2 {\r\n");
      out.write("        height: 400px;\r\n");
      out.write("        /* Tăng chiều cao biểu đồ */\r\n");
      out.write("        background-color: #f9f9f9;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        padding: 16px;\r\n");
      out.write("        /* Thêm khoảng cách bên trong */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card+.card {\r\n");
      out.write("        margin-top: 100px;\r\n");
      out.write("        /* Tăng khoảng cách giữa các khung biểu đồ */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Main Content */\r\n");
      out.write("    .card {\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        border: 1px solid #e0e0e0;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card h5 {\r\n");
      out.write("        font-size: 26px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #012970;\r\n");
      out.write("        margin-bottom: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table th {\r\n");
      out.write("        background-color: #f9f9f9;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table td,\r\n");
      out.write("    .table th {\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        border: 1px solid #e0e0e0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table .text-end {\r\n");
      out.write("        text-align: right;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .text-muted {\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .text-center {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        /* Căn giữa văn bản */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table tbody tr td {\r\n");
      out.write("        padding-left: 8px;\r\n");
      out.write("        /* Khoảng cách mặc định cho các chỉ tiêu */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table tbody tr td.sub-item {\r\n");
      out.write("        padding-left: 32px;\r\n");
      out.write("        /* Thụt lề cho các chỉ tiêu con */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media print {\r\n");
      out.write("\r\n");
      out.write("        .sidebar-main,\r\n");
      out.write("        .sidebar,\r\n");
      out.write("        .header,\r\n");
      out.write("        .back-to-top,\r\n");
      out.write("        .d-flex.justify-content-end,\r\n");
      out.write("            /* Ẩn các nút chức năng trên báo cáo */\r\n");
      out.write("        .sidebar-section,\r\n");
      out.write("        .breadcrumb,\r\n");
      out.write("        select,\r\n");
      out.write("        input[type=\"radio\"],\r\n");
      out.write("        input[type=\"date\"],\r\n");
      out.write("        label[for=\"report\"],\r\n");
      out.write("        label[for=\"month\"],\r\n");
      out.write("        label[for=\"quarter\"],\r\n");
      out.write("        label[for=\"year\"] {\r\n");
      out.write("            display: none !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body,\r\n");
      out.write("        .main,\r\n");
      out.write("        .main-content,\r\n");
      out.write("        .card {\r\n");
      out.write("            margin: 0 !important;\r\n");
      out.write("            padding: 0 !important;\r\n");
      out.write("            box-shadow: none !important;\r\n");
      out.write("            background: #fff !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .col-lg-9,\r\n");
      out.write("        .col-md-8 {\r\n");
      out.write("            width: 100% !important;\r\n");
      out.write("            max-width: 100% !important;\r\n");
      out.write("            flex: 0 0 100% !important;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Thêm thư viện SheetJS (đặt trước thẻ đóng </body>) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById('printReport').addEventListener('click', function () {\r\n");
      out.write("        window.print();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('exportExcel').addEventListener('click', function () {\r\n");
      out.write("        var wb = XLSX.utils.table_to_book(document.querySelector('table'), { sheet: \"Báo cáo\" });\r\n");
      out.write("        XLSX.writeFile(wb, 'baocaotaichinh.xlsx');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('sendEmail').addEventListener('click', function () {\r\n");
      out.write("        alert(\"Chức năng này đang phát triển\");\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
