/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-14 17:10:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"\r\n");
      out.write("    background-image: url('assets/img/background.jpg');\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-attachment: fixed;\r\n");
      out.write("    backdrop-filter: blur(2.5px); \">\r\n");
      out.write("<main>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-flex justify-content-center py-4\">\r\n");
      out.write("              <a href=\"homepage\" class=\"logo d-flex align-items-center w-auto\">\r\n");
      out.write("                <img src=\"assets/img/logo.png\" alt=\"\" height=\"38\">\r\n");
      out.write("                <span class=\"d-none d-lg-block\">AISHIBA</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"pt-4 pb-2\">\r\n");
      out.write("                  <h5 class=\"card-title text-center pb-0 fs-4\">Tạo tài khoản mới</h5>\r\n");
      out.write("                  <p class=\"text-center small\">Nhập thông tin cá nhân của bạn để tạo tài khoản</p>\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                  ");

                    String error = (String) request.getAttribute("error");
                    if (error != null) {
                  
      out.write("\r\n");
      out.write("                  <div class=\"alert alert-danger text-center small p-2\" role=\"alert\">\r\n");
      out.write("                    ");
      out.print( error );
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <form class=\"row g-3 needs-validation\" action=\"register\" method=\"post\" novalidate>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <label for=\"yourName\" class=\"form-label\">Họ và Tên</label>\r\n");
      out.write("                    <input type=\"text\" name=\"fullname\" class=\"form-control\" id=\"yourName\"\r\n");
      out.write("                           value=\"");
      out.print( request.getAttribute("fullname") != null ? request.getAttribute("fullname") : "" );
      out.write("\" required>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Vui lòng nhập họ và tên của bạn!</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <label for=\"yourUsername\" class=\"form-label\">Tên đăng nhập</label>\r\n");
      out.write("                    <div class=\"input-group has-validation\">\r\n");
      out.write("                      <span class=\"input-group-text\" id=\"inputGroupPrepend\">@</span>\r\n");
      out.write("                      <input type=\"text\" name=\"username\" class=\"form-control\" id=\"yourUsername\"\r\n");
      out.write("                             value=\"");
      out.print( request.getAttribute("username") != null ? request.getAttribute("username") : "" );
      out.write("\" required>\r\n");
      out.write("                      <div class=\"invalid-feedback\">Vui lòng chọn tên đăng nhập.</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <label for=\"yourEmail\" class=\"form-label\">Email</label>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" class=\"form-control\" id=\"yourEmail\"\r\n");
      out.write("                           value=\"");
      out.print( request.getAttribute("email") != null ? request.getAttribute("email") : "" );
      out.write("\" required>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Vui lòng nhập địa chỉ email hợp lệ.</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <label for=\"yourPassword\" class=\"form-label\">Mật khẩu</label>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" class=\"form-control\" id=\"yourPassword\" required>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Vui lòng nhập mật khẩu!</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <label for=\"confirmPassword\" class=\"form-label\">Xác nhận mật khẩu</label>\r\n");
      out.write("                    <input type=\"password\" name=\"confirm_password\" class=\"form-control\" id=\"confirmPassword\" required>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Vui lòng xác nhận lại mật khẩu!</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                      <input class=\"form-check-input\" name=\"terms\" type=\"checkbox\" value=\"true\" id=\"acceptTerms\" required>\r\n");
      out.write("                      <label class=\"form-check-label\" for=\"acceptTerms\">Tôi đồng ý với các <a href=\"#\">điều khoản và điều kiện</a></label>\r\n");
      out.write("                      <div class=\"invalid-feedback\">Bạn phải đồng ý với điều khoản để tiếp tục.</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <button class=\"btn btn-primary w-100\" type=\"submit\">Tạo tài khoản</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                    <p class=\"small mb-0\" style=\"color: black;\">Đã có tài khoản? <a href=\"login\">Đăng nhập</a></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"credits\" style=\"color: white;\">\r\n");
      out.write("              Designed by <a href=\"info\">Team seven</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</main>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "end.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
