/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-14 17:12:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import java.util.Iterator;

public final class report_005fcustomer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/apexcharts\"></script>\r\n");
      out.write("\r\n");
      out.write("<main id=\"main\" class=\"main\">\r\n");
      out.write("    <div class=\"pagetitle\">\r\n");
      out.write("        <h1>Báo cáo khách hàng</h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Trang chủ</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Thống kê</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\">Khách hàng</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-3 col-md-4 sidebar-main\">\r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <h5 class=\"mb-3\">Kiểu hiển thị</h5>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"displayType\" id=\"chart\" checked>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"chart\">Biểu đồ</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"displayType\" id=\"report\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"report\">Báo cáo</label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <h5 class=\"mb-3\">Mối quan tâm</h5>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"focus\" id=\"sales\" checked>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"sales\">Bán hàng</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"focus\" id=\"profit\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"profit\">Lợi nhuận</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"focus\" id=\"debt\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"debt\">Công nợ</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"focus\" id=\"customerSales\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"customerSales\">Hàng bán theo khách</label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <h5 class=\"mb-3\">Thời gian</h5>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"time\" id=\"thisWeek\" checked>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"thisWeek\">Tuần này</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"radio\" name=\"time\" id=\"custom\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"custom\">Lựa chọn khác</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"date\" class=\"form-control mt-2\" id=\"customDate\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <h5 class=\"mb-3\">Khách hàng</h5>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Theo mã, tên, điện thoại\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-9 col-md-8\">\r\n");
      out.write("            ");

                // Lấy dữ liệu từ request scope
                Map<String, Long> customerOrderCounts = (Map<String, Long>) request.getAttribute("customerOrderCounts");
                Map<String, Double> customerTotalPurchaseValues = (Map<String, Double>) request.getAttribute("customerTotalPurchaseValues");

                // Chuẩn bị dữ liệu cho JavaScript
                StringBuilder orderLabels = new StringBuilder();
                StringBuilder orderSeries = new StringBuilder();
                if (customerOrderCounts != null) {
                    Iterator<Map.Entry<String, Long>> it = customerOrderCounts.entrySet().iterator();
                    int count = 0;
                    while (it.hasNext() && count < 10) { // Giới hạn 10 khách hàng hàng đầu
                        Map.Entry<String, Long> entry = it.next();
                        orderLabels.append("'").append(entry.getKey()).append("'");
                        orderSeries.append(entry.getValue());
                        if (it.hasNext() && count < 9) { // Chỉ thêm dấu phẩy nếu không phải phần tử cuối cùng của top 10
                            orderLabels.append(", ");
                            orderSeries.append(", ");
                        }
                        count++;
                    }
                }

                StringBuilder purchaseLabels = new StringBuilder();
                StringBuilder purchaseSeries = new StringBuilder();
                if (customerTotalPurchaseValues != null) {
                    Iterator<Map.Entry<String, Double>> it = customerTotalPurchaseValues.entrySet().iterator();
                    int count = 0;
                    while (it.hasNext() && count < 10) { // Giới hạn 10 khách hàng hàng đầu
                        Map.Entry<String, Double> entry = it.next();
                        purchaseLabels.append("'").append(entry.getKey()).append("'");
                        purchaseSeries.append(entry.getValue());
                        if (it.hasNext() && count < 9) {
                            purchaseLabels.append(", ");
                            purchaseSeries.append(", ");
                        }
                        count++;
                    }
                }
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card p-4\">\r\n");
      out.write("                <h5 class=\"text-center\">Top 10 khách hàng mua nhiều nhất (Số lượng đơn hàng)</h5>\r\n");
      out.write("                <div id=\"customerOrderCountChart\" style=\"height: 600px;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card p-4 mt-5\">\r\n");
      out.write("                <h5 class=\"text-center\">Top 10 khách hàng theo Tổng Giá Trị Mua Hàng</h5>\r\n");
      out.write("                <div id=\"customerTotalPurchaseChart\" style=\"height: 600px;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Dữ liệu và cấu hình cho biểu đồ Top Khách Hàng theo Số Lượng Đơn Hàng\r\n");
      out.write("    var customerOrderCountOptions = {\r\n");
      out.write("        series: [{\r\n");
      out.write("            name: 'Số Lượng Đơn Hàng',\r\n");
      out.write("            data: [");
      out.print( orderSeries.toString() );
      out.write("]\r\n");
      out.write("        }],\r\n");
      out.write("        chart: {\r\n");
      out.write("            type: 'bar',\r\n");
      out.write("            height: 600,\r\n");
      out.write("            toolbar: { show: false }\r\n");
      out.write("        },\r\n");
      out.write("        colors: ['#42A5F5', '#66BB6A', '#FFA726', '#EF5350', '#AB47BC', '#7E57C2', '#26A69A', '#D4E157', '#FFCA28', '#8D6E63'],\r\n");
      out.write("        plotOptions: {\r\n");
      out.write("            bar: {\r\n");
      out.write("                horizontal: true,\r\n");
      out.write("                dataLabels: { position: 'top' },\r\n");
      out.write("                barHeight: '70%',\r\n");
      out.write("                distributed: true // Đảm bảo dòng này có!\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        dataLabels: {\r\n");
      out.write("            enabled: false, // Thay đổi từ 'true' thành 'false' để xóa các con số trên cột\r\n");
      out.write("            offsetX: -6,\r\n");
      out.write("            style: {\r\n");
      out.write("                fontSize: '12px',\r\n");
      out.write("                colors: ['#fff']\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        xaxis: {\r\n");
      out.write("            categories: [");
      out.print( orderLabels.toString() );
      out.write("],\r\n");
      out.write("            title: {\r\n");
      out.write("                text: 'Số Lượng Đơn Hàng'\r\n");
      out.write("            },\r\n");
      out.write("            labels: {\r\n");
      out.write("                style: {\r\n");
      out.write("                    fontSize: '14px',\r\n");
      out.write("                    colors: '#333'\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        yaxis: {\r\n");
      out.write("            labels: {\r\n");
      out.write("                style: {\r\n");
      out.write("                    fontSize: '14px',\r\n");
      out.write("                    colors: '#333'\r\n");
      out.write("                }\r\n");
      out.write("                // HÀM FORMATTER ĐÃ BỊ XÓA HOẶC KHÔNG CÓ Ở ĐÂY NỮA\r\n");
      out.write("                // Để hiển thị tên khách hàng đầy đủ, bạn chỉ cần xóa hàm formatter\r\n");
      out.write("                // Hoặc nếu muốn kiểm soát độ dài, bạn có thể điều chỉnh nó:\r\n");
      out.write("                // formatter: function (val) {\r\n");
      out.write("                //     if (val.length > 50) { // Ví dụ: cắt nếu dài hơn 50 ký tự\r\n");
      out.write("                //         return val.substring(0, 47) + '...';\r\n");
      out.write("                //     }\r\n");
      out.write("                //     return val;\r\n");
      out.write("                // }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    var customerOrderCountChart = new ApexCharts(document.querySelector(\"#customerOrderCountChart\"), customerOrderCountOptions);\r\n");
      out.write("    customerOrderCountChart.render();\r\n");
      out.write("\r\n");
      out.write("    // Dữ liệu và cấu hình cho biểu đồ Top Khách Hàng theo Tổng Giá Trị Mua Hàng\r\n");
      out.write("    var customerTotalPurchaseOptions = {\r\n");
      out.write("        series: [{\r\n");
      out.write("            name: 'Tổng Giá Trị Mua Hàng',\r\n");
      out.write("            data: [");
      out.print( purchaseSeries.toString() );
      out.write("]\r\n");
      out.write("        }],\r\n");
      out.write("        chart: {\r\n");
      out.write("            type: 'bar',\r\n");
      out.write("            height: 600,\r\n");
      out.write("            toolbar: { show: false }\r\n");
      out.write("        },\r\n");
      out.write("        colors: ['#42A5F5', '#66BB6A', '#FFA726', '#EF5350', '#AB47BC', '#7E57C2', '#26A69A', '#D4E157', '#FFCA28', '#8D6E63'], // Đặt ở đây\r\n");
      out.write("        plotOptions: {\r\n");
      out.write("            bar: {\r\n");
      out.write("                horizontal: true,\r\n");
      out.write("                dataLabels: { position: 'top' },\r\n");
      out.write("                barHeight: '70%',\r\n");
      out.write("                distributed: true // Quan trọng: Đảm bảo mỗi cột nhận một màu khác nhau từ mảng 'colors'\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        dataLabels: {\r\n");
      out.write("            enabled: false,\r\n");
      out.write("            offsetX: -6,\r\n");
      out.write("            style: {\r\n");
      out.write("                fontSize: '12px',\r\n");
      out.write("                colors: ['#fff']\r\n");
      out.write("            },\r\n");
      out.write("            formatter: function (val) {\r\n");
      out.write("                return val.toLocaleString('vi-VN', { style: 'currency', currency: 'VND' });\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        xaxis: {\r\n");
      out.write("            categories: [");
      out.print( purchaseLabels.toString() );
      out.write("],\r\n");
      out.write("            title: {\r\n");
      out.write("                text: 'Tổng Giá Trị Mua Hàng'\r\n");
      out.write("            },\r\n");
      out.write("            labels: {\r\n");
      out.write("                formatter: function (val) {\r\n");
      out.write("                    return val.toLocaleString('vi-VN', { style: 'currency', currency: 'VND' });\r\n");
      out.write("                },\r\n");
      out.write("                style: {\r\n");
      out.write("                    fontSize: '14px',\r\n");
      out.write("                    colors: '#333'\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        yaxis: {\r\n");
      out.write("            labels: {\r\n");
      out.write("                style: {\r\n");
      out.write("                    fontSize: '14px',\r\n");
      out.write("                    colors: '#333'\r\n");
      out.write("                }\r\n");
      out.write("                // HÀM FORMATTER ĐÃ BỊ XÓA HOẶC KHÔNG CÓ Ở ĐÂY NỮA\r\n");
      out.write("                // Để hiển thị tên khách hàng đầy đủ, bạn chỉ cần xóa hàm formatter\r\n");
      out.write("                // Hoặc nếu muốn kiểm soát độ dài, bạn có thể điều chỉnh nó:\r\n");
      out.write("                // formatter: function (val) {\r\n");
      out.write("                //     if (val.length > 50) { // Ví dụ: cắt nếu dài hơn 50 ký tự\r\n");
      out.write("                //         return val.substring(0, 47) + '...';\r\n");
      out.write("                //     }\r\n");
      out.write("                //     return val;\r\n");
      out.write("                // }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    var customerTotalPurchaseChart = new ApexCharts(document.querySelector(\"#customerTotalPurchaseChart\"), customerTotalPurchaseOptions);\r\n");
      out.write("    customerTotalPurchaseChart.render();\r\n");
      out.write("\r\n");
      out.write("    // JavaScript để ẩn/hiện ô input ngày tùy chỉnh\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("        const customTimeRadio = document.getElementById('custom');\r\n");
      out.write("        const thisWeekRadio = document.getElementById('thisWeek');\r\n");
      out.write("        const customDateInput = document.getElementById('customDate');\r\n");
      out.write("\r\n");
      out.write("        // Ẩn customDateInput ban đầu nếu \"Tuần này\" được chọn\r\n");
      out.write("        if (thisWeekRadio.checked) {\r\n");
      out.write("            customDateInput.style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        customTimeRadio.addEventListener('change', function () {\r\n");
      out.write("            if (this.checked) {\r\n");
      out.write("                customDateInput.style.display = 'block';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        thisWeekRadio.addEventListener('change', function () {\r\n");
      out.write("            if (this.checked) {\r\n");
      out.write("                customDateInput.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* Định vị sidebar trong main */\r\n");
      out.write("    .sidebar-main {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 70px;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        height: calc(100vh - 70px);\r\n");
      out.write("        z-index: 1020;\r\n");
      out.write("        overflow-y: auto;\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        border-left: 1px solid #e0e0e0;\r\n");
      out.write("        box-shadow: -2px 0 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        padding: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Đảm bảo nội dung chính không bị chồng lấn */\r\n");
      out.write("    .main-content {\r\n");
      out.write("        margin-right: 20%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Tùy chỉnh khung sidebar */\r\n");
      out.write("    .sidebar-wrapper {\r\n");
      out.write("        padding: 16px;\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Khung nhỏ cho từng phần */\r\n");
      out.write("    .card {\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        border: 1px solid #e0e0e0;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        padding: 24px;\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Tiêu đề của từng phần */\r\n");
      out.write("    .card h5 {\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #012970;\r\n");
      out.write("        margin-bottom: 16px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Tùy chỉnh từng phần trong sidebar */\r\n");
      out.write("    .sidebar-section {\r\n");
      out.write("        margin-bottom: 16px;\r\n");
      out.write("        padding: 16px;\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        border: 1px solid #e0e0e0;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Tiêu đề của từng phần */\r\n");
      out.write("    .sidebar-section h5 {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #012970;\r\n");
      out.write("        margin-bottom: 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Input và select */\r\n");
      out.write("    .sidebar-section .form-control,\r\n");
      out.write("    .sidebar-section .form-select {\r\n");
      out.write("        margin-top: 8px;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Radio button và nhãn */\r\n");
      out.write("    .sidebar-section .form-check {\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar-section .form-check-label {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .text-center .btn {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gap-3>* {\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end .btn {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end .btn+.btn {\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end {\r\n");
      out.write("        margin-top: -10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end .btn {\r\n");
      out.write("        padding: 8px 16px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .d-flex.justify-content-end .btn+.btn {\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #customerOrderCountChart,\r\n");
      out.write("    #customerTotalPurchaseChart {\r\n");
      out.write("        height: 600px; /* Cập nhật chiều cao phù hợp với chart.height */\r\n");
      out.write("        background-color: #f9f9f9;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        padding: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Điều chỉnh khoảng cách giữa các khung biểu đồ */\r\n");
      out.write("    .card + .card {\r\n");
      out.write("        margin-top: 50px;\r\n");
      out.write("    }\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
