/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-10 03:12:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class stock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/PC/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1747546064800L));
    _jspx_dependants.put("jar:file:/C:/Users/PC/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main id=\"main\" class=\"main\">\r\n");
      out.write("    <div class=\"pagetitle\">\r\n");
      out.write("        <h1>Nhập hàng</h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"homepage\">Trang chủ</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\">Giao dịch</li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\">Nhập hàng</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("                    <h5 class=\"card-title fs-4 text-primary mb-0\">Danh sách phiếu nhập hàng</h5>\r\n");
      out.write("                    <div class=\"d-flex gap-2\">\r\n");
      out.write("                        <button class=\"btn btn-primary d-flex align-items-center\" data-bs-toggle=\"modal\" data-bs-target=\"#newStockModal\">\r\n");
      out.write("                            <i class=\"bi bi-plus-lg me-1\"></i>\r\n");
      out.write("                            Tạo phiếu nhập\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button id=\"btnExportExcel\" class=\"btn btn-success d-flex align-items-center\">\r\n");
      out.write("                            <i class=\"bi bi-file-earmark-spreadsheet me-1\"></i>\r\n");
      out.write("                            Xuất Excel\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row mb-3\">\r\n");
      out.write("                    <div class=\"col-md-9 d-flex gap-2 align-items-center\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-text bg-light\"><i class=\"bi bi-search\"></i></span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"searchInput\" placeholder=\"Tìm theo mã phiếu, tên nhà cung cấp...\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <select id=\"statusFilter\" class=\"form-select\" style=\"width: auto;\">\r\n");
      out.write("                            <option value=\"\">Tất cả trạng thái</option>\r\n");
      out.write("                            <option value=\"CHO_XU_LY\">Chờ xử lý</option>\r\n");
      out.write("                            <option value=\"DA_THANH_TOAN\">Đã thanh toán</option>\r\n");
      out.write("                            <option value=\"DANG_GIAO_HANG\">Đang giao hàng</option>\r\n");
      out.write("                            <option value=\"DA_HUY\">Đã hủy</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <input type=\"date\" id=\"dateFilter\" class=\"form-control\" style=\"width: auto;\" title=\"Lọc theo ngày nhập hàng\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary\" id=\"resetFilters\">\r\n");
      out.write("                            <i class=\"bi bi-arrow-counterclockwise\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table table-hover align-middle\">\r\n");
      out.write("                        <thead class=\"table-light\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th style=\"width:40px\"><input type=\"checkbox\" class=\"form-check-input\" id=\"selectAllStock\"></th>\r\n");
      out.write("                            <th style=\"width:40px\">\r\n");
      out.write("                                <i class=\"bi bi-star header-star text-warning\" id=\"selectAllorderStars\" title=\"Chọn/Bỏ chọn tất cả nổi bật\" onclick=\"toggleSelectAllorderStars()\"></i>\r\n");
      out.write("                            </th>\r\n");
      out.write("                            <th>Mã PN</th>\r\n");
      out.write("                            <th>Thời gian</th>\r\n");
      out.write("                            <th>Nhà cung cấp</th>\r\n");
      out.write("                            <th class=\"text-end\">Tổng tiền nhập</th>\r\n");
      out.write("                            <th class=\"text-center\">Trạng thái</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody id=\"stockTableBody\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"6\" class=\"text-center p-4\">Đang tải dữ liệu...</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"pagination-container d-flex justify-content-center mt-3\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"newStockModal\" tabindex=\"-1\" aria-labelledby=\"newStockModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"newStockModalLabel\">Tạo phiếu nhập hàng mới</h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <form id=\"newStockForm\">\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label for=\"supplierName\" class=\"form-label\">Nhà cung cấp <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"supplierName\" placeholder=\"Nhập tên NCC để tìm...\" required>\r\n");
      out.write("                            <input type=\"hidden\" id=\"supplierId\" name=\"supplierId\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\"> <label for=\"stockDate\" class=\"form-label\">Ngày nhập hàng</label>\r\n");
      out.write("                            <input type=\"date\" class=\"form-control\" id=\"stockDate\" value=\"");
      out.print( new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()) );
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"stockAddress\" class=\"form-label\">Địa chỉ kho nhập <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"stockAddress\" placeholder=\"[Sẽ tự động điền khi chọn nhà cung cấp]\" required readonly>                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"mb-3\">Danh sách sản phẩm nhập</h6>\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"table table-bordered\" id=\"productImportTable\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th style=\"width: 35%;\">Tên sản phẩm</th>\r\n");
      out.write("                                <th style=\"width: 15%;\">Số lượng <span class=\"text-danger\">*</span></th>\r\n");
      out.write("                                <th style=\"width: 20%;\">Giá nhập <span class=\"text-danger\">*</span></th>\r\n");
      out.write("                                <th style=\"width: 20%;\">Thành tiền</th>\r\n");
      out.write("                                <th style=\"width: 10%;\">Xóa</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody id=\"productImportTableBody\"></tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-outline-primary mt-2\" onclick=\"addProductImportRow()\">+ Thêm sản phẩm</button>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mt-4 fs-5 text-end\">\r\n");
      out.write("                        <strong>Tổng tiền nhập: <span id=\"totalImportAmount\" class=\"text-danger fw-bold\">0</span> VND</strong>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" id=\"btnSaveNewStock\">Lưu phiếu nhập</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"stockDetailModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">Chi tiết phiếu nhập: <span id=\"modalStockCode\" class=\"text-primary\"></span></h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div id=\"modalDetailLoading\" class=\"text-center\"><div class=\"spinner-border\"></div></div>\r\n");
      out.write("                <div id=\"modalDetailContent\" class=\"d-none\">\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                        <div class=\"col-md-6\"><p><strong>Nhà cung cấp:</strong> <span id=\"modalSupplierName\"></span></p></div>\r\n");
      out.write("                        <div class=\"col-md-6\"><p><strong>Ngày nhập:</strong> <span id=\"modalstockDate\"></span></p></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                        <div class=\"col-md-6\"><p><strong>Địa chỉ kho:</strong> <span id=\"modalAddress\"></span></p></div>\r\n");
      out.write("                        <div class=\"col-md-6 d-flex align-items-center gap-2\">\r\n");
      out.write("                            <strong>Trạng thái:</strong>\r\n");
      out.write("                            <select id=\"modalStatusSelect\" class=\"form-select form-select-sm\" style=\"width: auto;\"></select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"mt-4\" style=\"font-size: 18px\">Các sản phẩm đã nhập</h6>\r\n");
      out.write("                    <table class=\"table table-sm table-bordered\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Sản phẩm</th>\r\n");
      out.write("                            <th class=\"text-end\">Số lượng</th>\r\n");
      out.write("                            <th class=\"text-end\">Giá nhập</th>\r\n");
      out.write("                            <th class=\"text-end\">Thành tiền</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody id=\"modalProductsTableBody\"></tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div class=\"d-flex justify-content-end gap-4 fs-5 mt-3\">\r\n");
      out.write("                        <strong>Tổng số lượng: <span id=\"modalTotalQuantity\" class=\"fw-bold text-primary\">0</span></strong>\r\n");
      out.write("                        <strong>Tổng giá trị: <span id=\"modalTotalAmount\" class=\"fw-bold text-danger\"></span></strong>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" id=\"btnUpdateStockStatus\">Lưu thay đổi</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /*Star*/\r\n");
      out.write("    .header-star,\r\n");
      out.write("    .bi-star,\r\n");
      out.write("    .bi-star-fill {\r\n");
      out.write("        color: #ffc107;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: all 0.2s;\r\n");
      out.write("        -webkit-text-stroke: 0.25px #ffc107;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .header-star:hover,\r\n");
      out.write("    .bi-star:hover,\r\n");
      out.write("    .bi-star-fill:hover {\r\n");
      out.write("        transform: scale(1.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .bi-star-fill {\r\n");
      out.write("        color: #ffc107 !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Style cho select box trong modal chi tiết */\r\n");
      out.write("    /* Style cho select box trong modal chi tiết */\r\n");
      out.write("    #modalStatusSelect {\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: .375rem; /* Thêm bo góc cho đẹp */\r\n");
      out.write("        padding-left: 12px;\r\n");
      out.write("        padding-right: 12px;\r\n");
      out.write("        /* THÊM MỚI: Tăng chiều rộng tối thiểu */\r\n");
      out.write("        min-width: 180px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* SỬA LẠI: Thêm !important để đảm bảo màu được áp dụng, ghi đè lên style mặc định */\r\n");
      out.write("    #modalStatusSelect.status-bg-CHO_XU_LY { background-color: #6c757d !important; color: white !important; }\r\n");
      out.write("    #modalStatusSelect.status-bg-DA_THANH_TOAN { background-color: #0d6efd !important; color: white !important; }\r\n");
      out.write("    #modalStatusSelect.status-bg-DANG_GIAO_HANG { background-color: #ffc107 !important; color: black !important; }\r\n");
      out.write("    #modalStatusSelect.status-bg-DA_HUY { background-color: #dc3545 !important; color: white !important; }\r\n");
      out.write("\r\n");
      out.write("    /* Thêm style cho các trạng thái o ben ngaoi */\r\n");
      out.write("    /* Status Badges */\r\n");
      out.write("    .status-badge { padding: 0.4em 0.7em; font-size: 0.85em; font-weight: 600; border-radius: .375rem; color: #fff; }\r\n");
      out.write("    .status-badge.status-PENDING { background-color: #ffc107; color: #000; }\r\n");
      out.write("    .status-badge.status-COMPLETED { background-color: #198754; }\r\n");
      out.write("    .status-badge.status-CANCELLED { background-color: #dc3545; }\r\n");
      out.write("\r\n");
      out.write("    /* Status Badges */\r\n");
      out.write("    .status-badge { padding: 0.4em 0.7em; font-size: 0.85em; font-weight: 600; border-radius: .375rem; color: #fff; }\r\n");
      out.write("\r\n");
      out.write("    /* Các màu mới cho trạng thái */\r\n");
      out.write("    .status-badge.status-CHO_XU_LY { background-color: #6c757d; } /* Xám */\r\n");
      out.write("    .status-badge.status-DA_THANH_TOAN { background-color: #0d6efd; } /* Xanh dương */\r\n");
      out.write("    .status-badge.status-DANG_GIAO_HANG { background-color: #ffc107; color: #000; } /* Vàng */\r\n");
      out.write("    .status-badge.status-DA_HUY { background-color: #dc3545; } /* Đỏ */\r\n");
      out.write("\r\n");
      out.write("    /* Các style khác của bạn... */\r\n");
      out.write("    .ui-autocomplete { z-index: 1056 !important; }\r\n");
      out.write("    .table > :not(caption) > * > * { vertical-align: middle; }\r\n");
      out.write("    #stockTableBody tr { cursor: pointer; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    // Thêm hàm helper này ở đâu đó bên ngoài $(document).ready()\r\n");
      out.write("    function updateStatusSelectColor(selectElement) {\r\n");
      out.write("        // Xóa tất cả các class màu cũ\r\n");
      out.write("        selectElement.removeClass('status-bg-CHO_XU_LY status-bg-DA_THANH_TOAN status-bg-DANG_GIAO_HANG status-bg-DA_HUY');\r\n");
      out.write("        // Thêm class màu mới tương ứng với giá trị được chọn\r\n");
      out.write("        selectElement.addClass('status-bg-' + selectElement.val());\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    //Star và checkbox\r\n");
      out.write("    /**\r\n");
      out.write("     * Bật/tắt trạng thái chọn của tất cả các checkbox đơn hàng.\r\n");
      out.write("     * @param {HTMLInputElement} masterCheckbox Checkbox tổng ở tiêu đề bảng.\r\n");
      out.write("     */\r\n");
      out.write("    function toggleSelectAllorder(masterCheckbox) {\r\n");
      out.write("        // 1. Tìm tất cả các checkbox của từng đơn hàng trong tbody\r\n");
      out.write("        //    Lưu ý: class '.supplier-checkbox' là class bạn đã dùng cho các checkbox ở dòng.\r\n");
      out.write("        const rowCheckboxes = document.querySelectorAll('#orderTableBody .supplier-checkbox');\r\n");
      out.write("\r\n");
      out.write("        // 2. Lặp qua từng checkbox và đặt trạng thái 'checked' của nó\r\n");
      out.write("        //    giống với trạng thái của checkbox tổng.\r\n");
      out.write("        rowCheckboxes.forEach(checkbox => {\r\n");
      out.write("            checkbox.checked = masterCheckbox.checked;\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /**\r\n");
      out.write("     * Bật/tắt trạng thái \"đánh dấu sao\" của tất cả các đơn hàng.\r\n");
      out.write("     * @param {HTMLElement} masterStar Icon ngôi sao tổng ở tiêu đề bảng.\r\n");
      out.write("     */\r\n");
      out.write("    function toggleSelectAllorderStars(masterStar) {\r\n");
      out.write("        // 1. Xác định xem hành động cần làm là \"tô màu\" hay \"bỏ tô màu\"\r\n");
      out.write("        //    dựa vào trạng thái hiện tại của ngôi sao tổng.\r\n");
      out.write("        //    Nếu ngôi sao tổng là rỗng (có class 'bi-star'), thì chúng ta cần tô màu.\r\n");
      out.write("        const shouldBeFilled = masterStar.classList.contains('bi-star');\r\n");
      out.write("\r\n");
      out.write("        // 2. Tìm tất cả các icon ngôi sao của từng đơn hàng trong tbody\r\n");
      out.write("        const rowStars = document.querySelectorAll('#orderTableBody .bi-star, #orderTableBody .bi-star-fill');\r\n");
      out.write("\r\n");
      out.write("        // 3. Lặp qua từng ngôi sao và thay đổi class của nó\r\n");
      out.write("        rowStars.forEach(star => {\r\n");
      out.write("            if (shouldBeFilled) {\r\n");
      out.write("                // Tô màu ngôi sao\r\n");
      out.write("                star.classList.remove('bi-star');\r\n");
      out.write("                star.classList.add('bi-star-fill', 'text-warning'); // Thêm class màu vàng\r\n");
      out.write("            } else {\r\n");
      out.write("                // Bỏ tô màu ngôi sao\r\n");
      out.write("                star.classList.remove('bi-star-fill', 'text-warning');\r\n");
      out.write("                star.classList.add('bi-star');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 4. Cập nhật lại chính ngôi sao tổng\r\n");
      out.write("        if (shouldBeFilled) {\r\n");
      out.write("            masterStar.classList.remove('bi-star');\r\n");
      out.write("            masterStar.classList.add('bi-star-fill', 'text-warning');\r\n");
      out.write("        } else {\r\n");
      out.write("            masterStar.classList.remove('bi-star-fill', 'text-warning');\r\n");
      out.write("            masterStar.classList.add('bi-star');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Script cho ngôi sao\r\n");
      out.write("    const headerStar = document.querySelector('#selectAllorderStars');\r\n");
      out.write("    const rowStars = document.querySelectorAll('tbody tr td:nth-child(2) i');\r\n");
      out.write("    headerStar.addEventListener('click', function() {\r\n");
      out.write("        const isHeaderStarFilled = this.classList.contains('bi-star-fill');\r\n");
      out.write("        if (isHeaderStarFilled) {\r\n");
      out.write("            this.classList.remove('bi-star-fill');\r\n");
      out.write("            this.classList.add('bi-star');\r\n");
      out.write("        } else {\r\n");
      out.write("            this.classList.remove('bi-star');\r\n");
      out.write("            this.classList.add('bi-star-fill');\r\n");
      out.write("        }\r\n");
      out.write("        rowStars.forEach(star => {\r\n");
      out.write("            if (isHeaderStarFilled) {\r\n");
      out.write("                star.classList.remove('bi-star-fill');\r\n");
      out.write("                star.classList.add('bi-star');\r\n");
      out.write("            } else {\r\n");
      out.write("                star.classList.remove('bi-star');\r\n");
      out.write("                star.classList.add('bi-star-fill');\r\n");
      out.write("            }\r\n");
      out.write("            const orderId = star.closest('tr').querySelector('td:nth-child(3)').textContent;\r\n");
      out.write("            localStorage.setItem(`favorite_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, !isHeaderStarFilled);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    rowStars.forEach(star => {\r\n");
      out.write("        star.addEventListener('click', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            if (this.classList.contains('bi-star-fill')) {\r\n");
      out.write("                this.classList.remove('bi-star-fill');\r\n");
      out.write("                this.classList.add('bi-star');\r\n");
      out.write("            } else {\r\n");
      out.write("                this.classList.remove('bi-star');\r\n");
      out.write("                this.classList.add('bi-star-fill');\r\n");
      out.write("            }\r\n");
      out.write("            const orderId = this.closest('tr').querySelector('td:nth-child(3)').textContent;\r\n");
      out.write("            const isFavorite = this.classList.contains('bi-star-fill');\r\n");
      out.write("            localStorage.setItem(`favorite_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, isFavorite);\r\n");
      out.write("            updateHeaderStar();\r\n");
      out.write("        });\r\n");
      out.write("        const orderId = star.closest('tr').querySelector('td:nth-child(3)').textContent;\r\n");
      out.write("        const isFavorite = localStorage.getItem(`favorite_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`) === 'true';\r\n");
      out.write("        if (isFavorite) {\r\n");
      out.write("            star.classList.remove('bi-star');\r\n");
      out.write("            star.classList.add('bi-star-fill');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function updateHeaderStar() {\r\n");
      out.write("        const allStarsFilled = Array.from(rowStars).every(star => star.classList.contains('bi-star-fill'));\r\n");
      out.write("        if (allStarsFilled) {\r\n");
      out.write("            headerStar.classList.remove('bi-star');\r\n");
      out.write("            headerStar.classList.add('bi-star-fill');\r\n");
      out.write("        } else {\r\n");
      out.write("            headerStar.classList.remove('bi-star-fill');\r\n");
      out.write("            headerStar.classList.add('bi-star');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    updateHeaderStar();\r\n");
      out.write("\r\n");
      out.write("    // Hàm format tiền tệ để sử dụng chung\r\n");
      out.write("    const currencyFormatter = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' });\r\n");
      out.write("\r\n");
      out.write("    // ===================================================================\r\n");
      out.write("    //  CÁC HÀM TIỆN ÍCH CHO MODAL TẠO MỚI (để ở ngoài khối ready)\r\n");
      out.write("    // ===================================================================\r\n");
      out.write("    function addProductImportRow() {\r\n");
      out.write("        const rowHtml =\r\n");
      out.write("            '<tr>' +\r\n");
      out.write("            '<td><input type=\"text\" class=\"form-control product-search\" placeholder=\"Gõ tên hoặc mã SP...\"><input type=\"hidden\" class=\"product-id\"></td>' +\r\n");
      out.write("            '<td><input type=\"number\" class=\"form-control import-quantity\" min=\"1\" value=\"1\"></td>' +\r\n");
      out.write("            '<td><input type=\"number\" class=\"form-control import-price\" readonly value=\"\"></td>' +\r\n");
      out.write("            '<td><input type=\"text\" class=\"form-control sub-total\" readonly value=\"\"></td>' +\r\n");
      out.write("            '<td><button type=\"button\" class=\"btn btn-danger btn-sm\" onclick=\"removeProductImportRow(this)\">Xóa</button></td>' +\r\n");
      out.write("            '</tr>';\r\n");
      out.write("        $('#productImportTableBody').append(rowHtml);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function removeProductImportRow(button) {\r\n");
      out.write("        $(button).closest('tr').remove();\r\n");
      out.write("        updateTotalImportAmount();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function updateTotalImportAmount() {\r\n");
      out.write("        let totalAmount = 0;\r\n");
      out.write("        $('#productImportTableBody tr').each(function() {\r\n");
      out.write("            const row = $(this);\r\n");
      out.write("            const quantity = parseFloat(row.find('.import-quantity').val()) || 0;\r\n");
      out.write("            const price = parseFloat(row.find('.import-price').val()) || 0;\r\n");
      out.write("            totalAmount += quantity * price;\r\n");
      out.write("        });\r\n");
      out.write("        $('#totalImportAmount').text(currencyFormatter.format(totalAmount));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    // ===================================================================\r\n");
      out.write("    //  KHỐI JQUERY CHÍNH\r\n");
      out.write("    // ===================================================================\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        // --- KHAI BÁO BIẾN ---\r\n");
      out.write("        const searchInput = $('#searchInput');\r\n");
      out.write("        const statusFilter = $('#statusFilter');\r\n");
      out.write("        const dateFilter = $('#dateFilter');\r\n");
      out.write("        const tableBody = $('#stockTableBody');\r\n");
      out.write("        const paginationContainer = $('.pagination-container');\r\n");
      out.write("        const detailModal = new bootstrap.Modal(document.getElementById('stockDetailModal'));\r\n");
      out.write("        const newStockModal = new bootstrap.Modal(document.getElementById('newStockModal'));\r\n");
      out.write("        let currentStockId = null;\r\n");
      out.write("        let debounceTimeout;\r\n");
      out.write("\r\n");
      out.write("        // --- CÁC HÀM RENDER ---\r\n");
      out.write("        function renderTable(stocks) {\r\n");
      out.write("            tableBody.empty();\r\n");
      out.write("            if (!stocks || stocks.length === 0) {\r\n");
      out.write("                tableBody.html('<tr><td colspan=\"6\" class=\"text-center p-4\">Không có phiếu nhập nào.</td></tr>');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            $.each(stocks, function(index, stock) {\r\n");
      out.write("                const row =\r\n");
      out.write("                    '<tr data-id=\"' + stock.id + '\" style=\"cursor:pointer;\">' +\r\n");
      out.write("                    '<td><input type=\"checkbox\" class=\"form-check-input\" onclick=\"event.stopPropagation();\"></td>' +\r\n");
      out.write("                    '<td><i class=\"bi bi-star star-outline\" onclick=\"toggleSupplierStar(this, event)\"></i></td>' +\r\n");
      out.write("                    '<td class=\"text-primary\">' + stock.formattedId + '</td>' +\r\n");
      out.write("                    '<td>' + stock.stockDate + '</td>' +\r\n");
      out.write("                    '<td>' + stock.supplierName + '</td>' +\r\n");
      out.write("                    '<td class=\"text-end\">' + currencyFormatter.format(stock.totalAmount) + '</td>' +\r\n");
      out.write("                    '<td class=\"text-center\"><span class=\"status-badge status-' + stock.status + '\">' + stock.statusDisplay + '</span></td>' +\r\n");
      out.write("                    '</tr>';\r\n");
      out.write("                tableBody.append(row);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // HÀM PHÂN TRANG HOÀN CHỈNH\r\n");
      out.write("        function renderPagination(totalPages, currentPage) {\r\n");
      out.write("            paginationContainer.empty();\r\n");
      out.write("            if (totalPages <= 1) return;\r\n");
      out.write("            currentPage = parseInt(currentPage);\r\n");
      out.write("            let paginationHtml = '<ul class=\"pagination\">';\r\n");
      out.write("            paginationHtml += '<li class=\"page-item ' + (currentPage === 1 ? 'disabled' : '') + '\"><a class=\"page-link\" href=\"#\" data-page=\"' + (currentPage - 1) + '\">Trước</a></li>';\r\n");
      out.write("            let startPage = Math.max(1, currentPage - 2), endPage = Math.min(totalPages, currentPage + 2);\r\n");
      out.write("            if (startPage > 1) {\r\n");
      out.write("                paginationHtml += '<li class=\"page-item\"><a class=\"page-link\" href=\"#\" data-page=\"1\">1</a></li>';\r\n");
      out.write("                if (startPage > 2) paginationHtml += '<li class=\"page-item disabled\"><span class=\"page-link\">...</span></li>';\r\n");
      out.write("            }\r\n");
      out.write("            for (let i = startPage; i <= endPage; i++) {\r\n");
      out.write("                paginationHtml += '<li class=\"page-item ' + (i === currentPage ? 'active' : '') + '\"><a class=\"page-link\" href=\"#\" data-page=\"' + i + '\">' + i + '</a></li>';\r\n");
      out.write("            }\r\n");
      out.write("            if (endPage < totalPages) {\r\n");
      out.write("                if (endPage < totalPages - 1) paginationHtml += '<li class=\"page-item disabled\"><span class=\"page-link\">...</span></li>';\r\n");
      out.write("                paginationHtml += '<li class=\"page-item\"><a class=\"page-link\" href=\"#\" data-page=\"' + totalPages + '\">' + totalPages + '</a></li>';\r\n");
      out.write("            }\r\n");
      out.write("            paginationHtml += '<li class=\"page-item ' + (currentPage === totalPages ? 'disabled' : '') + '\"><a class=\"page-link\" href=\"#\" data-page=\"' + (currentPage + 1) + '\">Sau</a></li>';\r\n");
      out.write("            paginationHtml += '</ul>';\r\n");
      out.write("            paginationContainer.html(paginationHtml);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // --- HÀM AJAX CHÍNH ---\r\n");
      out.write("        function fetchAndRenderStock(page = 1) {\r\n");
      out.write("            tableBody.html('<tr><td colspan=\"6\" class=\"text-center p-4\"><div class=\"spinner-border spinner-border-sm\"></div> Đang tải...</td></tr>');\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: 'stock',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                data: { action: 'searchAndFilter', searchTerm: searchInput.val(), status: statusFilter.val(), date: dateFilter.val(), page: page },\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                success: function(response) { renderTable(response.stocks); renderPagination(response.totalPages, response.currentPage); },\r\n");
      out.write("                error: function() { tableBody.html('<tr><td colspan=\"6\" class=\"text-center text-danger p-4\">Lỗi tải dữ liệu.</td></tr>'); }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // --- GÁN CÁC SỰ KIỆN ---\r\n");
      out.write("\r\n");
      out.write("        // 1. Lọc và tìm kiếm\r\n");
      out.write("        searchInput.on('keyup', () => { clearTimeout(debounceTimeout); debounceTimeout = setTimeout(() => fetchAndRenderStock(1), 500); });\r\n");
      out.write("        statusFilter.add(dateFilter).on('change', () => fetchAndRenderStock(1));\r\n");
      out.write("        $('#resetFilters').on('click', () => { searchInput.val(''); statusFilter.val(''); dateFilter.val(''); fetchAndRenderStock(1); });\r\n");
      out.write("\r\n");
      out.write("        // 2. Phân trang\r\n");
      out.write("        paginationContainer.on('click', '.page-link', function(e) { e.preventDefault(); const page = $(this).data('page'); if(page) fetchAndRenderStock(page); });\r\n");
      out.write("\r\n");
      out.write("        // 3. Click vào dòng để xem chi tiết (HOÀN THIỆN)\r\n");
      out.write("// Tìm đến hàm click vào dòng để xem chi tiết\r\n");
      out.write("        tableBody.on('click', 'tr', function() {\r\n");
      out.write("            currentStockId = $(this).data('id');\r\n");
      out.write("            if (!currentStockId) return;\r\n");
      out.write("\r\n");
      out.write("            $('#modalDetailContent').addClass('d-none');\r\n");
      out.write("            $('#modalDetailLoading').removeClass('d-none');\r\n");
      out.write("            detailModal.show();\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: 'stock',\r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                data: { action: 'getDetails', id: currentStockId },\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("\r\n");
      out.write("                // THAY THẾ TOÀN BỘ KHỐI SUCCESS BẰNG KHỐI NÀY\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                    if (!response.stock) {\r\n");
      out.write("                        alert('Không thể tải chi tiết phiếu nhập.');\r\n");
      out.write("                        detailModal.hide();\r\n");
      out.write("                        return;\r\n");
      out.write("                    }\r\n");
      out.write("                    const stock = response.stock;\r\n");
      out.write("\r\n");
      out.write("                    // Điền dữ liệu chung vào modal\r\n");
      out.write("                    $('#modalStockCode').text(stock.id);\r\n");
      out.write("                    $('#modalSupplierName').text(stock.supplier.name);\r\n");
      out.write("                    $('#modalstockDate').text(new Date(stock.stockDate).toLocaleString('vi-VN'));\r\n");
      out.write("                    $('#modalAddress').text(stock.address);\r\n");
      out.write("\r\n");
      out.write("                    // SỬA LỖI: Luôn gọi .empty() TRƯỚC khi thêm mới để xóa các option cũ\r\n");
      out.write("                    const statusSelect = $('#modalStatusSelect').empty();\r\n");
      out.write("                    const statuses = { 'CHO_XU_LY': 'Chờ xử lý', 'DA_THANH_TOAN': 'Đã thanh toán', 'DANG_GIAO_HANG': 'Đang giao hàng', 'DA_HUY': 'Đã hủy' };\r\n");
      out.write("                    $.each(statuses, (key, value) => {\r\n");
      out.write("                        statusSelect.append('<option value=\"' + key + '\"' + (key === stock.status ? ' selected' : '') + '>' + value + '</option>');\r\n");
      out.write("                    });\r\n");
      out.write("                    // Gọi hàm đổi màu cho select box\r\n");
      out.write("                    updateStatusSelectColor(statusSelect);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    // Điền bảng sản phẩm VÀ TÍNH TỔNG SỐ LƯỢNG\r\n");
      out.write("                    const productsBody = $('#modalProductsTableBody').empty();\r\n");
      out.write("                    let totalAmount = 0;\r\n");
      out.write("                    let totalQuantity = 0; // THÊM MỚI: Biến đếm tổng số lượng\r\n");
      out.write("\r\n");
      out.write("                    $.each(stock.products, function(i, item) {\r\n");
      out.write("                        const subTotal = item.quantity * item.importPrice;\r\n");
      out.write("                        totalAmount += subTotal;\r\n");
      out.write("                        totalQuantity += item.quantity; // THÊM MỚI: Cộng dồn số lượng\r\n");
      out.write("\r\n");
      out.write("                        productsBody.append(\r\n");
      out.write("                            '<tr>' +\r\n");
      out.write("                            '<td>' + item.name + '</td>' +\r\n");
      out.write("                            '<td class=\"text-end\">' + item.quantity + '</td>' +\r\n");
      out.write("                            '<td class=\"text-end\">' + currencyFormatter.format(item.importPrice) + '</td>' +\r\n");
      out.write("                            '<td class=\"text-end\">' + currencyFormatter.format(subTotal) + '</td>' +\r\n");
      out.write("                            '</tr>'\r\n");
      out.write("                        );\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    // Cập nhật giá trị lên giao diện\r\n");
      out.write("                    $('#modalTotalQuantity').text(totalQuantity); // THÊM MỚI: Hiển thị tổng số lượng\r\n");
      out.write("                    $('#modalTotalAmount').text(currencyFormatter.format(totalAmount));\r\n");
      out.write("\r\n");
      out.write("                    // Hiển thị nội dung\r\n");
      out.write("                    $('#modalDetailLoading').addClass('d-none');\r\n");
      out.write("                    $('#modalDetailContent').removeClass('d-none');\r\n");
      out.write("                },\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    alert('Lỗi kết nối máy chủ khi lấy chi tiết phiếu nhập.');\r\n");
      out.write("                    detailModal.hide();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 4. Cập nhật trạng thái (HOÀN THIỆN)\r\n");
      out.write("        $('#btnUpdateStockStatus').on('click', function() {\r\n");
      out.write("            const newStatus = $('#modalStatusSelect').val();\r\n");
      out.write("            if (!currentStockId || !newStatus) return;\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: 'stock?action=updateStatus', type: 'POST', contentType: 'application/json',\r\n");
      out.write("                data: JSON.stringify({ stockId: currentStockId, status: newStatus }),\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                    if (response.success) { alert('Cập nhật thành công!'); detailModal.hide(); fetchAndRenderStock(); }\r\n");
      out.write("                    else { alert('Lỗi: ' + (response.error || 'Không thể cập nhật.')); }\r\n");
      out.write("                },\r\n");
      out.write("                error: () => alert('Lỗi kết nối máy chủ.')\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 5. Logic cho modal tạo mới (HOÀN THIỆN)\r\n");
      out.write("        $(\"#supplierName\").autocomplete({\r\n");
      out.write("            source: (req, res) => $.ajax({ url: \"stock\", data: { action: 'searchSuppliers', term: req.term }, dataType: \"json\", success: data => res(data) }),\r\n");
      out.write("            minLength: 1,\r\n");
      out.write("            appendTo: \"#newStockForm\",\r\n");
      out.write("            select: function(event, ui) { // Sửa lại thành function để dễ đọc\r\n");
      out.write("                // Điền tên và ID nhà cung cấp\r\n");
      out.write("                $(\"#supplierName\").val(ui.item.name);\r\n");
      out.write("                $(\"#supplierId\").val(ui.item.value);\r\n");
      out.write("\r\n");
      out.write("                // THÊM DÒNG NÀY: Lấy địa chỉ từ `ui.item` và điền vào ô địa chỉ\r\n");
      out.write("                $(\"#stockAddress\").val(ui.item.address);\r\n");
      out.write("\r\n");
      out.write("                return false; // Ngăn không cho autocomplete điền giá trị \"label\" vào input\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('#productImportTableBody').on('focus', '.product-search', function() {\r\n");
      out.write("            $(this).autocomplete({\r\n");
      out.write("                source: (req, res) => $.ajax({ url: \"stock\", data: { action: 'searchProducts', term: req.term }, dataType: \"json\", success: data => res(data) }),\r\n");
      out.write("                minLength: 1, appendTo: \"#newStockForm\",\r\n");
      out.write("                select: (event, ui) => {\r\n");
      out.write("                    const row = $(this).closest('tr');\r\n");
      out.write("                    row.find('.product-search').val(ui.item.name);\r\n");
      out.write("                    row.find('.product-id').val(ui.item.value);\r\n");
      out.write("                    row.find('.import-price').val(ui.item.price).trigger('input'); // Lấy giá bán làm giá nhập tạm thời\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('#productImportTableBody').on('input', '.import-quantity, .import-price', function() {\r\n");
      out.write("            const row = $(this).closest('tr');\r\n");
      out.write("            const quantity = parseFloat(row.find('.import-quantity').val()) || 0;\r\n");
      out.write("            const price = parseFloat(row.find('.import-price').val()) || 0;\r\n");
      out.write("            row.find('.sub-total').val(currencyFormatter.format(quantity * price));\r\n");
      out.write("            updateTotalImportAmount();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('#btnSaveNewStock').on('click', function() {\r\n");
      out.write("            if (!$('#supplierId').val()) { alert('Vui lòng chọn nhà cung cấp.'); return; }\r\n");
      out.write("            const products = [];\r\n");
      out.write("            let validProducts = true;\r\n");
      out.write("            $('#productImportTableBody tr').each(function() {\r\n");
      out.write("                const row = $(this);\r\n");
      out.write("                const p = { toyId: row.find('.product-id').val(), quantity: parseFloat(row.find('.import-quantity').val()), importPrice: parseFloat(row.find('.import-price').val()) };\r\n");
      out.write("                if (!p.toyId || !p.quantity || p.quantity <= 0 || isNaN(p.importPrice)) { validProducts = false; return; }\r\n");
      out.write("                products.push(p);\r\n");
      out.write("            });\r\n");
      out.write("            if (!validProducts || products.length === 0) { alert('Vui lòng thêm ít nhất một sản phẩm hợp lệ.'); return; }\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: 'stock?action=create',\r\n");
      out.write("                type: 'POST',\r\n");
      out.write("                contentType: 'application/json',\r\n");
      out.write("                // Chỉ gửi những dữ liệu mà server cần\r\n");
      out.write("                data: JSON.stringify({\r\n");
      out.write("                    supplierId: $('#supplierId').val(),\r\n");
      out.write("                    stockDate: $('#stockDate').val(),\r\n");
      out.write("                    products: products\r\n");
      out.write("                }),\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                    if (response.success) {\r\n");
      out.write("                        alert('Tạo phiếu nhập thành công!');\r\n");
      out.write("                        // Dùng bootstrap.Modal.getInstance để gọi phương thức hide\r\n");
      out.write("                        bootstrap.Modal.getInstance(document.getElementById('newStockModal')).hide();\r\n");
      out.write("                        fetchAndRenderStock(1);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert('Lỗi: ' + (response.message || 'Không thể tạo phiếu nhập.'));\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error: () => alert('Lỗi kết nối khi tạo phiếu nhập.')\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('#modalStatusSelect').on('change', function() {\r\n");
      out.write("            updateStatusSelectColor($(this));\r\n");
      out.write("        });\r\n");
      out.write("        // --- KHỞI CHẠY LẦN ĐẦU ---\r\n");
      out.write("        fetchAndRenderStock(1);\r\n");
      out.write("    });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
