/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-14 17:17:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("        .sticky-top {\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        z-index: 1020;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Đảm bảo danh mục hiển thị phía trên */\r\n");
      out.write("    #navbar-vertical {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 65px; /* Đặt vị trí ngay dưới thanh navbar */\r\n");
      out.write("        left: 0;\r\n");
      out.write("        z-index: 1050; /* Đảm bảo nó hiển thị trên các phần tử khác */\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Khi danh mục được mở */\r\n");
      out.write("    #navbar-vertical.show {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Đảm bảo các phần tử khác không bị che */\r\n");
      out.write("    .container-fluid {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- Cart Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"row px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-8 table-responsive mb-5\">\r\n");
      out.write("                <table class=\"table table-bordered text-center mb-0\">\r\n");
      out.write("                    <thead class=\"bg-secondary text-dark\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Sản phẩm</th>\r\n");
      out.write("                            <th>Giá</th>\r\n");
      out.write("                            <th>Số lượng</th>\r\n");
      out.write("                            <th>Tổng</th>\r\n");
      out.write("                            <th>Xóa</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody class=\"align-middle\" id=\"cartItems\">\r\n");
      out.write("                        <tr data-id=\"1\">\r\n");
      out.write("                            <td class=\"align-middle\"><img src=\"img/product-1.jpg\" alt=\"\" style=\"width: 50px;\"> Đồ chơi trẻ em\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"align-middle price\">150000</td>\r\n");
      out.write("                            <td class=\"align-middle\">\r\n");
      out.write("                                <div class=\"input-group quantity mx-auto\" style=\"width: 100px;\">\r\n");
      out.write("                                    <div class=\"input-group-btn\">\r\n");
      out.write("                                        <button class=\"btn btn-sm btn-primary btn-minus\">\r\n");
      out.write("                                            <i class=\"fa fa-minus\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control form-control-sm bg-secondary text-center quantity-input\"\r\n");
      out.write("                                        value=\"1\">\r\n");
      out.write("                                    <div class=\"input-group-btn\">\r\n");
      out.write("                                        <button class=\"btn btn-sm btn-primary btn-plus\">\r\n");
      out.write("                                            <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"align-middle total\">150000</td>\r\n");
      out.write("                            <td class=\"align-middle\"><button class=\"btn btn-sm btn-primary btn-remove\"><i class=\"fa fa-times\"></i>\r\n");
      out.write("                                </button></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"card border-secondary mb-5\">\r\n");
      out.write("                    <div class=\"card-header bg-secondary border-0\">\r\n");
      out.write("                        <h4 class=\"font-weight-semi-bold m-0\">Tóm tắt giỏ hàng</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-3 pt-1\">\r\n");
      out.write("                            <h6 class=\"font-weight-medium\">Tạm tính</h6>\r\n");
      out.write("                            <h6 class=\"font-weight-medium\">150.000₫</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                            <h6 class=\"font-weight-medium\">Phí vận chuyển</h6>\r\n");
      out.write("                            <h6 class=\"font-weight-medium\">30.000₫</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer border-secondary bg-transparent\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mt-2\">\r\n");
      out.write("                            <h5 class=\"font-weight-bold\">Tổng cộng</h5>\r\n");
      out.write("                            <h5 class=\"font-weight-bold\">180.000₫</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"btn btn-block btn-primary my-3 py-3\" onclick=\"window.location.href='checkout'\">Tiến hành thanh toán</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Cart End -->\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("            // --- Hiển thị sản phẩm từ localStorage ---\r\n");
      out.write("            const cartItems = document.getElementById(\"cartItems\");\r\n");
      out.write("            const totalElement = document.querySelector(\".card-footer .font-weight-bold:last-child\");\r\n");
      out.write("            const cartCount = document.getElementById(\"cartCount\");\r\n");
      out.write("\r\n");
      out.write("            // Lấy giỏ hàng từ localStorage\r\n");
      out.write("            function getCart() {\r\n");
      out.write("                return JSON.parse(localStorage.getItem('cart') || '[]');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Lưu giỏ hàng vào localStorage\r\n");
      out.write("            function setCart(cart) {\r\n");
      out.write("                localStorage.setItem('cart', JSON.stringify(cart));\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Cập nhật số lượng trên icon\r\n");
      out.write("            function updateCartCount() {\r\n");
      out.write("                const cart = getCart();\r\n");
      out.write("                const total = cart.reduce((sum, item) => sum + (item.quantity || 1), 0);\r\n");
      out.write("                if (cartCount) cartCount.textContent = total;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Hiển thị sản phẩm trong bảng\r\n");
      out.write("            function renderCart() {\r\n");
      out.write("                const cart = getCart();\r\n");
      out.write("                cartItems.innerHTML = '';\r\n");
      out.write("                let subtotal = 0;\r\n");
      out.write("                if (cart.length === 0) {\r\n");
      out.write("                    cartItems.innerHTML = `<tr><td colspan=\"5\">Giỏ hàng trống.</td></tr>`;\r\n");
      out.write("                } else {\r\n");
      out.write("                    cart.forEach((item, idx) => {\r\n");
      out.write("                        const itemTotal = item.price * item.quantity;\r\n");
      out.write("                        subtotal += itemTotal;\r\n");
      out.write("                        cartItems.innerHTML += `\r\n");
      out.write("                            <tr data-id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                <td class=\"align-middle\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                                <td class=\"align-middle price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.price.toLocaleString()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("₫</td>\r\n");
      out.write("                                <td class=\"align-middle\">\r\n");
      out.write("                                    <div class=\"input-group quantity mx-auto\" style=\"width: 100px;\">\r\n");
      out.write("                                        <div class=\"input-group-btn\">\r\n");
      out.write("                                            <button class=\"btn btn-sm btn-primary btn-minus\">\r\n");
      out.write("                                                <i class=\"fa fa-minus\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control form-control-sm bg-secondary text-center quantity-input\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                        <div class=\"input-group-btn\">\r\n");
      out.write("                                            <button class=\"btn btn-sm btn-primary btn-plus\">\r\n");
      out.write("                                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"align-middle total\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemTotal.toLocaleString()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("₫</td>\r\n");
      out.write("                                <td class=\"align-middle\"><button class=\"btn btn-sm btn-primary btn-remove\"><i class=\"fa fa-times\"></i>\r\n");
      out.write("                                    </button></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        `;\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("                updateSummary(subtotal);\r\n");
      out.write("                updateCartCount();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Cập nhật tổng tiền và tóm tắt giỏ hàng\r\n");
      out.write("            function updateSummary(subtotal) {\r\n");
      out.write("                // Phí vận chuyển cố định 30.000₫ nếu có hàng, 0 nếu trống\r\n");
      out.write("                let shipping = subtotal > 0 ? 30000 : 0;\r\n");
      out.write("                let total = subtotal + shipping;\r\n");
      out.write("\r\n");
      out.write("                // Cập nhật tóm tắt giỏ hàng\r\n");
      out.write("                document.querySelector(\".card-body .d-flex.mb-3.pt-1 h6:last-child\").textContent = subtotal.toLocaleString() + \"₫\";\r\n");
      out.write("                document.querySelector(\".card-body .d-flex:last-child h6:last-child\").textContent = shipping.toLocaleString() + \"₫\";\r\n");
      out.write("                document.querySelector(\".card-footer .font-weight-bold:last-child\").textContent = total.toLocaleString() + \"₫\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Xử lý tăng/giảm/xóa sản phẩm\r\n");
      out.write("            cartItems.addEventListener(\"click\", function (e) {\r\n");
      out.write("                const cart = getCart();\r\n");
      out.write("                const row = e.target.closest(\"tr\");\r\n");
      out.write("                if (!row) return;\r\n");
      out.write("                const idx = parseInt(row.getAttribute(\"data-id\"));\r\n");
      out.write("                if (e.target.closest(\".btn-plus\")) {\r\n");
      out.write("                    cart[idx].quantity++;\r\n");
      out.write("                    setCart(cart);\r\n");
      out.write("                    renderCart();\r\n");
      out.write("                }\r\n");
      out.write("                if (e.target.closest(\".btn-minus\")) {\r\n");
      out.write("                    if (cart[idx].quantity > 1) {\r\n");
      out.write("                        cart[idx].quantity--;\r\n");
      out.write("                        setCart(cart);\r\n");
      out.write("                        renderCart();\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                if (e.target.closest(\".btn-remove\")) {\r\n");
      out.write("                    cart.splice(idx, 1);\r\n");
      out.write("                    setCart(cart);\r\n");
      out.write("                    renderCart();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Xử lý nhập số lượng trực tiếp\r\n");
      out.write("            cartItems.addEventListener(\"change\", function (e) {\r\n");
      out.write("                if (e.target.classList.contains(\"quantity-input\")) {\r\n");
      out.write("                    const row = e.target.closest(\"tr\");\r\n");
      out.write("                    const idx = parseInt(row.getAttribute(\"data-id\"));\r\n");
      out.write("                    let val = parseInt(e.target.value) || 1;\r\n");
      out.write("                    if (val < 1) val = 1;\r\n");
      out.write("                    const cart = getCart();\r\n");
      out.write("                    cart[idx].quantity = val;\r\n");
      out.write("                    setCart(cart);\r\n");
      out.write("                    renderCart();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Khởi tạo giỏ hàng khi tải trang\r\n");
      out.write("            renderCart();\r\n");
      out.write("\r\n");
      out.write("            // --- Đổi màu header cho đồng bộ và userNav ---\r\n");
      out.write("            document.querySelectorAll('.bg-primary').forEach(e => e.style.background = '#D19C97');\r\n");
      out.write("            document.querySelectorAll('.text-primary').forEach(e => e.style.color = '#D19C97');\r\n");
      out.write("            document.querySelectorAll('.badge-primary').forEach(e => e.style.background = '#D19C97');\r\n");
      out.write("            document.querySelectorAll('.nav-link.active').forEach(e => e.style.color = '#D19C97');\r\n");
      out.write("\r\n");
      out.write("            // Hiển thị liên kết user_info nếu đã đăng nhập\r\n");
      out.write("            const userNav = document.getElementById('userNav');\r\n");
      out.write("            const loginData = JSON.parse(localStorage.getItem('rememberLogin') || '{}');\r\n");
      out.write("            const userData = JSON.parse(localStorage.getItem('aishibaUser') || '{}');\r\n");
      out.write("            let isLoggedIn = false;\r\n");
      out.write("            let userName = '';\r\n");
      out.write("\r\n");
      out.write("            if (\r\n");
      out.write("                (loginData.email === 'user1@example.com' && loginData.password === '12345678') ||\r\n");
      out.write("                (loginData.email === 'admin' && loginData.password === '123456') ||\r\n");
      out.write("                (userData.email && loginData.email === userData.email && loginData.password === userData.password)\r\n");
      out.write("            ) {\r\n");
      out.write("                isLoggedIn = true;\r\n");
      out.write("                userName = userData.name || loginData.email;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (isLoggedIn && userNav) {\r\n");
      out.write("                userNav.innerHTML = `\r\n");
      out.write("                    <a href=\"user_info\" class=\"nav-item nav-link\" style=\"color:#D19C97;\">\r\n");
      out.write("                        <i class=\"fa fa-user text-primary mr-2\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName ? userName : 'Tài khoản của tôi'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\" class=\"nav-item nav-link\" id=\"logoutNav\" style=\"color:#D19C97;\">\r\n");
      out.write("                        <i class=\"fa fa-sign-out-alt text-primary mr-2\"></i>Đăng xuất\r\n");
      out.write("                    </a>\r\n");
      out.write("                `;\r\n");
      out.write("                document.getElementById('logoutNav').addEventListener('click', function(e) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    localStorage.removeItem('rememberLogin');\r\n");
      out.write("                    window.location.reload();\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Thêm chức năng liên kết danh mục tới shop và lọc theo danh mục\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            document.querySelectorAll('#navbar-vertical .nav-item.nav-link').forEach(function(link) {\r\n");
      out.write("                link.style.cursor = 'pointer';\r\n");
      out.write("                link.addEventListener('click', function(e) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    const category = this.textContent.trim();\r\n");
      out.write("                    window.location.href = 'shop?category=' + encodeURIComponent(category);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
