/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-14 17:17:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1747546064800L));
    _jspx_dependants.put("jar:file:/C:/Users/PC/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Product Detail Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"row px-xl-5\">\r\n");
      out.write("            <!-- Hình ảnh sản phẩm -->\r\n");
      out.write("            <div class=\"col-lg-5\">\r\n");
      out.write("                <img class=\"img-fluid w-100 border\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-1.jpg\" alt=\"Sản phẩm\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Thông tin sản phẩm -->\r\n");
      out.write("            <div class=\"col-lg-7\">\r\n");
      out.write("                <h3 class=\"font-weight-semi-bold\">Đồ Chơi Lắp Ráp Thùng Gạch Sáng Tạo: Xe Hơi Và Xe Tải LEGO DUPLO 10439 (80 Chi Tiết)</h3>\r\n");
      out.write("                <p class=\"mb-2\"><strong>Thương hiệu:</strong> <a href=\"#\" class=\"text-primary\">LEGO DUPLO</a></p>\r\n");
      out.write("                <p class=\"mb-2\"><strong>SKU:</strong> 10439</p>\r\n");
      out.write("                <h4 class=\"text-primary mb-3\">977.000đ <small class=\"text-muted\"><del>1.629.000đ</del></small> <span class=\"badge badge-danger\">-40%</span></h4>\r\n");
      out.write("                <ul class=\"list-unstyled mb-4\">\r\n");
      out.write("                    <li><i class=\"fa fa-check text-primary mr-2\"></i> Hàng chính hãng</li>\r\n");
      out.write("                    <li><i class=\"fa fa-check text-primary mr-2\"></i> Miễn phí giao hàng toàn quốc đơn trên 500k</li>\r\n");
      out.write("                    <li><i class=\"fa fa-check text-primary mr-2\"></i> Giao hàng hỏa tốc 4 tiếng</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"d-flex align-items-center mb-4\">\r\n");
      out.write("                    <label class=\"mr-3\">Số lượng:</label>\r\n");
      out.write("                    <div class=\"input-group quantity mr-3\" style=\"width: 130px;\">\r\n");
      out.write("                        <div class=\"input-group-btn\">\r\n");
      out.write("                            <button class=\"btn btn-primary btn-minus\">\r\n");
      out.write("                                <i class=\"fa fa-minus\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control bg-secondary text-center\" value=\"1\">\r\n");
      out.write("                        <div class=\"input-group-btn\">\r\n");
      out.write("                            <button class=\"btn btn-primary btn-plus\">\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-primary px-3\"><i class=\"fa fa-shopping-cart mr-1\"></i> Thêm vào giỏ hàng</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"mb-4\"><strong>Dự kiến các cửa hàng đang còn sản phẩm:</strong></p>\r\n");
      out.write("                <div class=\"border p-3 mb-3\">\r\n");
      out.write("                    <p class=\"mb-1\"><strong>[CHA093] MYKINGDOM TRƯỜNG CHINH Q12</strong></p>\r\n");
      out.write("                    <p class=\"mb-1\">70 Trường Chinh, Phường Tân Hưng Thuận, Quận 12, Thành phố Hồ Chí Minh</p>\r\n");
      out.write("                    <p class=\"mb-0\"><i class=\"fa fa-phone text-primary mr-2\"></i>+842836200987</p>\r\n");
      out.write("                    <p class=\"text-success mt-2\">Còn: <strong>10</strong> sản phẩm</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Tab thông tin sản phẩm -->\r\n");
      out.write("        <div class=\"row px-xl-5 mt-5\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <div class=\"nav nav-tabs border-secondary mb-4\">\r\n");
      out.write("                    <a class=\"nav-item nav-link text-dark active\" data-toggle=\"tab\" href=\"#tab-description\">Mô tả</a>\r\n");
      out.write("                    <a class=\"nav-item nav-link text-dark\" data-toggle=\"tab\" href=\"#tab-information\">Thông tin kỹ thuật</a>\r\n");
      out.write("                    <a class=\"nav-item nav-link text-dark\" data-toggle=\"tab\" href=\"#tab-reviews\">Đánh giá (3)</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("                    <!-- Mô tả sản phẩm -->\r\n");
      out.write("                    <div class=\"tab-pane fade show active\" id=\"tab-description\">\r\n");
      out.write("                        <h4 class=\"mb-3\">Mô tả sản phẩm</h4>\r\n");
      out.write("                        <p>Đồ chơi lắp ráp thùng gạch sáng tạo giúp trẻ phát triển tư duy sáng tạo, kỹ năng vận động và khả năng giải quyết vấn đề. Sản phẩm phù hợp cho trẻ từ 1 tuổi trở lên.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Thông tin kỹ thuật -->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"tab-information\">\r\n");
      out.write("                        <h4 class=\"mb-3\">Thông tin kỹ thuật</h4>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><strong>Thương hiệu:</strong> LEGO DUPLO</li>\r\n");
      out.write("                            <li><strong>SKU:</strong> 10439</li>\r\n");
      out.write("                            <li><strong>Chất liệu:</strong> Nhựa ABS an toàn</li>\r\n");
      out.write("                            <li><strong>Số lượng chi tiết:</strong> 80</li>\r\n");
      out.write("                            <li><strong>Độ tuổi phù hợp:</strong> 1+ tuổi</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Đánh giá sản phẩm -->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"tab-reviews\">\r\n");
      out.write("                        <h4 class=\"mb-3\">Đánh giá từ khách hàng</h4>\r\n");
      out.write("                        <div class=\"media mb-4\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/user.jpg\" alt=\"User\" class=\"img-fluid mr-3 mt-1\" style=\"width: 45px;\">\r\n");
      out.write("                            <div class=\"media-body\">\r\n");
      out.write("                                <h6>Nguyễn Văn A<small> - <i>01/05/2025</i></small></h6>\r\n");
      out.write("                                <div class=\"text-primary mb-2\">\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa fa-star-half-alt\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p>Sản phẩm rất tốt, bé nhà mình rất thích!</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"media mb-4\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/user.jpg\" alt=\"User\" class=\"img-fluid mr-3 mt-1\" style=\"width: 45px;\">\r\n");
      out.write("                            <div class=\"media-body\">\r\n");
      out.write("                                <h6>Trần Thị B<small> - <i>28/04/2025</i></small></h6>\r\n");
      out.write("                                <div class=\"text-primary mb-2\">\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p>Chất lượng tuyệt vời, giao hàng nhanh chóng.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Product Detail End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // Lấy ID sản phẩm từ URL\r\n");
      out.write("        const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("        const productId = urlParams.get('id');\r\n");
      out.write("\r\n");
      out.write("        // Hiển thị ID sản phẩm (hoặc tải thông tin sản phẩm từ server)\r\n");
      out.write("        console.log(\"ID sản phẩm:\", productId);\r\n");
      out.write("        \r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    // Đổi màu các thành phần header cho đồng bộ\r\n");
      out.write("    document.querySelectorAll('.bg-primary').forEach(e => e.style.background = '#D19C97');\r\n");
      out.write("    document.querySelectorAll('.text-primary').forEach(e => e.style.color = '#D19C97');\r\n");
      out.write("    document.querySelectorAll('.badge-primary').forEach(e => e.style.background = '#D19C97');\r\n");
      out.write("    document.querySelectorAll('.nav-link.active').forEach(e => e.style.color = '#D19C97');\r\n");
      out.write("\r\n");
      out.write("    // Hiển thị liên kết user_info nếu đã đăng nhập\r\n");
      out.write("    const userNav = document.getElementById('userNav');\r\n");
      out.write("    const loginData = JSON.parse(localStorage.getItem('rememberLogin') || '{}');\r\n");
      out.write("    const userData = JSON.parse(localStorage.getItem('aishibaUser') || '{}');\r\n");
      out.write("    let isLoggedIn = false;\r\n");
      out.write("    let userName = '';\r\n");
      out.write("\r\n");
      out.write("    // Kiểm tra đăng nhập với tài khoản mặc định hoặc tài khoản đã đăng ký\r\n");
      out.write("    if (\r\n");
      out.write("        (loginData.email === 'user1@example.com' && loginData.password === '12345678') ||\r\n");
      out.write("        (loginData.email === 'admin' && loginData.password === '123456') ||\r\n");
      out.write("        (userData.email && loginData.email === userData.email && loginData.password === userData.password)\r\n");
      out.write("    ) {\r\n");
      out.write("        isLoggedIn = true;\r\n");
      out.write("        userName = userData.name || loginData.email;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (isLoggedIn && userNav) {\r\n");
      out.write("        userNav.innerHTML = `\r\n");
      out.write("            <a href=\"user_info\" class=\"nav-item nav-link\" style=\"color:#D19C97;\">\r\n");
      out.write("                <i class=\"fa fa-user text-primary mr-2\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName ? userName : 'Tài khoản của tôi'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"nav-item nav-link\" id=\"logoutNav\" style=\"color:#D19C97;\">\r\n");
      out.write("                <i class=\"fa fa-sign-out-alt text-primary mr-2\"></i>Đăng xuất\r\n");
      out.write("            </a>\r\n");
      out.write("        `;\r\n");
      out.write("        document.getElementById('logoutNav').addEventListener('click', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            localStorage.removeItem('rememberLogin');\r\n");
      out.write("            window.location.reload();\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    // Liên kết danh mục sang shop và lọc theo danh mục\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        document.querySelectorAll('#navbar-vertical .nav-item.nav-link').forEach(function(link) {\r\n");
      out.write("            link.style.cursor = 'pointer';\r\n");
      out.write("            link.addEventListener('click', function(e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                const category = this.textContent.trim();\r\n");
      out.write("                window.location.href = 'shop?category=' + encodeURIComponent(category);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Hàm lấy giỏ hàng từ localStorage\r\n");
      out.write("    function getCart() {\r\n");
      out.write("        return JSON.parse(localStorage.getItem('cart') || '[]');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Hàm lưu giỏ hàng vào localStorage\r\n");
      out.write("    function setCart(cart) {\r\n");
      out.write("        localStorage.setItem('cart', JSON.stringify(cart));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Hàm cập nhật số lượng sản phẩm trên icon giỏ hàng\r\n");
      out.write("    function updateCartCount() {\r\n");
      out.write("        const cart = getCart();\r\n");
      out.write("        const total = cart.reduce((sum, item) => sum + (item.quantity || 1), 0);\r\n");
      out.write("        const cartCount = document.getElementById('cartCount');\r\n");
      out.write("        if (cartCount) cartCount.textContent = total;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Hàm thêm sản phẩm vào giỏ hàng (lưu cả id, tên, giá)\r\n");
      out.write("    function addToCart(productId, productName, price, quantity) {\r\n");
      out.write("        let cart = getCart();\r\n");
      out.write("        let found = false;\r\n");
      out.write("        cart = cart.map(item => {\r\n");
      out.write("            if (item.id === productId) {\r\n");
      out.write("                found = true;\r\n");
      out.write("                return { ...item, quantity: (item.quantity || 1) + quantity };\r\n");
      out.write("            }\r\n");
      out.write("            return item;\r\n");
      out.write("        });\r\n");
      out.write("        if (!found) {\r\n");
      out.write("            cart.push({ id: productId, name: productName, price: price, quantity: quantity });\r\n");
      out.write("        }\r\n");
      out.write("        setCart(cart);\r\n");
      out.write("        updateCartCount();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Hàm hiển thị modal thông báo thành công\r\n");
      out.write("    function showSuccessModal(productName, price) {\r\n");
      out.write("        let oldModal = document.getElementById('successModal');\r\n");
      out.write("        if (oldModal) oldModal.remove();\r\n");
      out.write("\r\n");
      out.write("        let modal = document.createElement('div');\r\n");
      out.write("        modal.id = 'successModal';\r\n");
      out.write("        modal.style.position = 'fixed';\r\n");
      out.write("        modal.style.top = '0';\r\n");
      out.write("        modal.style.left = '0';\r\n");
      out.write("        modal.style.width = '100vw';\r\n");
      out.write("        modal.style.height = '100vh';\r\n");
      out.write("        modal.style.background = 'rgba(0,0,0,0.35)';\r\n");
      out.write("        modal.style.display = 'flex';\r\n");
      out.write("        modal.style.alignItems = 'center';\r\n");
      out.write("        modal.style.justifyContent = 'center';\r\n");
      out.write("        modal.style.zIndex = 10000;\r\n");
      out.write("\r\n");
      out.write("        modal.innerHTML = `\r\n");
      out.write("            <div style=\"background:#fff; border-radius:12px; max-width:480px; width:90%; padding:36px 32px 28px 32px; box-shadow:0 8px 32px rgba(0,0,0,0.18); text-align:center; position:relative;\">\r\n");
      out.write("                <div style=\"margin-bottom:18px;\">\r\n");
      out.write("                    <svg width=\"80\" height=\"80\" viewBox=\"0 0 80 80\">\r\n");
      out.write("                        <circle cx=\"40\" cy=\"40\" r=\"38\" fill=\"none\" stroke=\"#d4f5dd\" stroke-width=\"4\"/>\r\n");
      out.write("                        <polyline points=\"25,43 37,55 56,30\" fill=\"none\" stroke=\"#6fcf97\" stroke-width=\"5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2 style=\"font-weight:700; color:#444; margin-bottom:12px;\">Thành công!</h2>\r\n");
      out.write("                <div style=\"color:#555; font-size:1.1rem; margin-bottom:24px;\">\r\n");
      out.write("                    Sản phẩm <b>\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"</b> đã được thêm vào giỏ hàng với giá <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price.toLocaleString()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("₫</b>.\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"cart\" id=\"successModalOk\" style=\"display:inline-block;padding:8px 32px; font-size:1.1rem; border:none; border-radius:8px; background:#7b7be6; color:#fff; font-weight:600; box-shadow:0 2px 8px rgba(123,123,230,0.08); cursor:pointer; text-decoration:none;\">Xem giỏ hàng</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        `;\r\n");
      out.write("        document.body.appendChild(modal);\r\n");
      out.write("\r\n");
      out.write("        modal.addEventListener('click', function(e) {\r\n");
      out.write("            if (e.target === modal) modal.remove();\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Gắn sự kiện cho nút \"Thêm vào giỏ hàng\" và tăng/giảm số lượng\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        updateCartCount();\r\n");
      out.write("\r\n");
      out.write("        // Lấy productId từ URL hoặc mặc định\r\n");
      out.write("        const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("        const productId = urlParams.get('id') || '10439';\r\n");
      out.write("\r\n");
      out.write("        // Lấy tên và giá sản phẩm từ DOM\r\n");
      out.write("        const productName = document.querySelector('h3.font-weight-semi-bold')?.textContent.trim() || 'Sản phẩm';\r\n");
      out.write("        const priceText = document.querySelector('h4.text-primary')?.childNodes[0]?.textContent || '';\r\n");
      out.write("        // Chuyển giá về số\r\n");
      out.write("        const price = parseInt(priceText.replace(/[^\\d]/g, ''));\r\n");
      out.write("\r\n");
      out.write("        // Xử lý tăng/giảm số lượng\r\n");
      out.write("        let quantityInput = document.querySelector('.quantity input');\r\n");
      out.write("        let btnPlus = document.querySelector('.btn-plus');\r\n");
      out.write("        let btnMinus = document.querySelector('.btn-minus');\r\n");
      out.write("        if (btnPlus && quantityInput) {\r\n");
      out.write("            btnPlus.addEventListener('click', function() {\r\n");
      out.write("                let val = parseInt(quantityInput.value) || 1;\r\n");
      out.write("                quantityInput.value = val + 1;\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        if (btnMinus && quantityInput) {\r\n");
      out.write("            btnMinus.addEventListener('click', function() {\r\n");
      out.write("                let val = parseInt(quantityInput.value) || 1;\r\n");
      out.write("                if (val > 1) quantityInput.value = val - 1;\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Sự kiện thêm vào giỏ hàng\r\n");
      out.write("        const addBtn = document.querySelector('.btn-primary.px-3');\r\n");
      out.write("        if (addBtn && quantityInput) {\r\n");
      out.write("            addBtn.addEventListener('click', function() {\r\n");
      out.write("                const quantity = parseInt(quantityInput.value) || 1;\r\n");
      out.write("                addToCart(productId, productName, price, quantity);\r\n");
      out.write("                showSuccessModal(productName, price);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    </script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
