/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-10 03:22:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Aishiba - Cửa hàng đồ chơi</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Cửa hàng đồ chơi chất lượng cao\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Cửa hàng đồ chơi Aishiba - Đồ chơi trẻ em, đồ chơi giáo dục, đồ chơi mô hình\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/logo.png\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write("        .sticky-top {\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        z-index: 1020;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Đảm bảo danh mục hiển thị phía trên */\r\n");
      out.write("    #navbar-vertical {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 65px; /* Đặt vị trí ngay dưới thanh navbar */\r\n");
      out.write("        left: 0;\r\n");
      out.write("        z-index: 1050; /* Đảm bảo nó hiển thị trên các phần tử khác */\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Khi danh mục được mở */\r\n");
      out.write("    #navbar-vertical.show {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Đảm bảo các phần tử khác không bị che */\r\n");
      out.write("    .container-fluid {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <div class=\"sticky-top\">\r\n");
      out.write("        <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-light\">\r\n");
      out.write("        <div class=\"row py-2 px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-6 d-none d-lg-block\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a class=\"text-dark\" href=\"\">FAQs</a>\r\n");
      out.write("                    <span class=\"text-muted px-2\">|</span>\r\n");
      out.write("                    <a class=\"text-dark\" href=\"\">Trợ giúp</a>\r\n");
      out.write("                    <span class=\"text-muted px-2\">|</span>\r\n");
      out.write("                    <a class=\"text-dark\" href=\"\">Hỗ trợ</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row align-items-center py-3 px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                <a href=\"homepage\" class=\"text-decoration-none\">\r\n");
      out.write("                    <h1 class=\"m-0 display-5 font-weight-semi-bold\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/logo.png\" height=\"42\" alt=\"Aishiba\"> <span class=\"text-primary\">Aishiba</span></h1>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 col-6 text-left\">\r\n");
      out.write("                <form id=\"searchForm\" action=\"shop\" method=\"get\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"searchInput\" name=\"q\" placeholder=\"Tìm kiếm sản phẩm...\">\r\n");
      out.write("                        <div class=\"input-group-append\">\r\n");
      out.write("                            <button type=\"submit\" class=\"input-group-text bg-transparent text-primary\" id=\"searchBtn\">\r\n");
      out.write("                                <i class=\"fa fa-search\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-6 text-right\">\r\n");
      out.write("                <a href=\"cart\" class=\"btn border\">\r\n");
      out.write("                    <i class=\"fas fa-shopping-cart text-primary\"></i>\r\n");
      out.write("                    <span id=\"cartCount\" class=\"badge\">0</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid mb-5\">\r\n");
      out.write("        <div class=\"row border-top px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                <a class=\"btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100\" \r\n");
      out.write("                   data-toggle=\"collapse\" href=\"#navbar-vertical\" \r\n");
      out.write("                   style=\"height: 65px; margin-top: -1px; padding: 0 30px;\">\r\n");
      out.write("                    <h6 class=\"m-0\">Danh mục</h6>\r\n");
      out.write("                    <i class=\"fa fa-angle-down text-dark\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <nav class=\"collapse navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0\" \r\n");
      out.write("                     id=\"navbar-vertical\">\r\n");
      out.write("                    <div class=\"navbar-nav w-100 overflow-hidden\" style=\"height: auto;\">\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Đồ chơi trẻ em</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Đồ chơi giáo dục</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Đồ chơi mô hình</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Đồ chơi vận động</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Đồ chơi xếp hình</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Thú bông</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">Robot</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-9\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0\">\r\n");
      out.write("                    <a href=\"homepage\" class=\"text-decoration-none d-block d-lg-none\">\r\n");
      out.write("                        <h1 class=\"m-0 display-5 font-weight-semi-bold\"><span class=\"text-primary\">Aishiba</span></h1>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarCollapse\">\r\n");
      out.write("                        <div class=\"navbar-nav mr-auto py-0\">\r\n");
      out.write("                            <a href=\"homepage\" class=\"nav-item nav-link active\">Trang chủ</a>\r\n");
      out.write("                            <a href=\"shop\" class=\"nav-item nav-link\">Cửa hàng</a>\r\n");
      out.write("                            <a href=\"contact\" class=\"nav-item nav-link\">Liên hệ</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"navbar-nav ml-auto py-0\" id=\"userNav\">\r\n");
      out.write("                            <a href=\"login\" class=\"nav-item nav-link\" id=\"loginNav\">\r\n");
      out.write("                                <i class=\"fa fa-user text-primary mr-2\"></i>Đăng nhập\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
