/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-10 03:22:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* Đảm bảo danh mục hiển thị phía trên */\r\n");
      out.write("    #navbar-vertical {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 65px; /* Đặt vị trí ngay dưới thanh navbar */\r\n");
      out.write("        left: 0;\r\n");
      out.write("        z-index: 1050; /* Đảm bảo nó hiển thị trên các phần tử khác */\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Khi danh mục được mở */\r\n");
      out.write("    #navbar-vertical.show {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Đảm bảo các phần tử khác không bị che */\r\n");
      out.write("    .container-fluid {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("  \r\n");
      out.write("    <!-- Carousel Start -->\r\n");
      out.write("    <div id=\"header-carousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\" style=\"height: 410px;\">\r\n");
      out.write("                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/carousel-1.jpg\" alt=\"Image\">\r\n");
      out.write("                <div class=\"carousel-caption d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"p-3\" style=\"max-width: 700px;\">\r\n");
      out.write("                        <h4 class=\"text-light text-uppercase font-weight-medium mb-3\">Giảm giá 10% cho đơn hàng đầu tiên</h4>\r\n");
      out.write("                        <h3 class=\"display-4 text-white font-weight-semi-bold mb-4\">Đồ chơi nổi bật</h3>\r\n");
      out.write("                        <a href=\"shop\" class=\"btn btn-light py-2 px-3\">Mua ngay</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\" style=\"height: 410px;\">\r\n");
      out.write("                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/carousel-2.jpg\" alt=\"Image\">\r\n");
      out.write("                <div class=\"carousel-caption d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"p-3\" style=\"max-width: 700px;\">\r\n");
      out.write("                        <h4 class=\"text-light text-uppercase font-weight-medium mb-3\">Ưu đãi đặc biệt</h4>\r\n");
      out.write("                        <h3 class=\"display-4 text-white font-weight-semi-bold mb-4\">Đồ chơi giáo dục</h3>\r\n");
      out.write("                        <a href=\"shop\" class=\"btn btn-light py-2 px-3\">Khám phá</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#header-carousel\" data-slide=\"prev\">\r\n");
      out.write("            <div class=\"btn btn-dark\" style=\"width: 45px; height: 45px;\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon mb-n2\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#header-carousel\" data-slide=\"next\">\r\n");
      out.write("            <div class=\"btn btn-dark\" style=\"width: 45px; height: 45px;\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon mb-n2\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Carousel End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Featured Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"row px-xl-5 pb-3\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"d-flex align-items-center border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <h1 class=\"fa fa-check text-primary m-0 mr-3\"></h1>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Sản phẩm chất lượng</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"d-flex align-items-center border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <h1 class=\"fa fa-shipping-fast text-primary m-0 mr-3\"></h1>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Miễn phí giao hàng</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"d-flex align-items-center border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <h1 class=\"fas fa-exchange-alt text-primary m-0 mr-3\"></h1>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Đổi trả trong 14 ngày</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"d-flex align-items-center border mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                    <h1 class=\"fa fa-phone-volume text-primary m-0 mr-3\"></h1>\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold m-0\">Hỗ trợ 24/7</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Featured End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Products Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"text-center mb-4\">\r\n");
      out.write("            <h2 class=\"section-title px-5\"><span class=\"px-2\">Sản phẩm nổi bật</span></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row px-xl-5 pb-3\">\r\n");
      out.write("            <!-- Product Card 1 -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <a href=\"detail\">\r\n");
      out.write("                            <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-1.jpg\" alt=\"Robot đồ chơi\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Robot đồ chơi thông minh</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>2,500,000 VNĐ</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"detail\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết</a>\r\n");
      out.write("                        <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Robot đồ chơi thông minh', 2500000)\">\r\n");
      out.write("                            <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Product Card 2 -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <a href=\"detail\">\r\n");
      out.write("                            <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-2.jpg\" alt=\"Đồ chơi giáo dục\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Đồ chơi giáo dục sáng tạo</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>1,200,000 VNĐ</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"detail\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết</a>\r\n");
      out.write("                        <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Đồ chơi giáo dục sáng tạo', 1200000)\">\r\n");
      out.write("                            <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Product Card 3 -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <a href=\"detail\">\r\n");
      out.write("                            <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-3.jpg\" alt=\"Đồ chơi mô hình\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Đồ chơi mô hình xe hơi</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>850,000 VNĐ</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"detail\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết</a>\r\n");
      out.write("                        <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Đồ chơi mô hình xe hơi', 850000)\">\r\n");
      out.write("                            <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Product Card 4 -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                <div class=\"card product-item border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                        <a href=\"detail\">\r\n");
      out.write("                            <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-9.jpg\" alt=\"Đồ chơi vận động\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                        <h6 class=\"text-truncate mb-3\">Đồ chơi vận động ngoài trời</h6>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                            <h6>1,500,000 VNĐ</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                        <a href=\"detail\" class=\"btn btn-sm text-dark p-0\"><i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết</a>\r\n");
      out.write("                        <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Đồ chơi vận động ngoài trời', 1500000)\">\r\n");
      out.write("                            <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Products End -->\r\n");
      out.write("    <script>\r\n");
      out.write("        // Hàm lấy giỏ hàng từ localStorage\r\n");
      out.write("    function getCart() {\r\n");
      out.write("        return JSON.parse(localStorage.getItem('cart') || '[]');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Hàm lưu giỏ hàng vào localStorage\r\n");
      out.write("    function setCart(cart) {\r\n");
      out.write("        localStorage.setItem('cart', JSON.stringify(cart));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Hàm cập nhật số lượng sản phẩm trên icon giỏ hàng\r\n");
      out.write("    function updateCartCount() {\r\n");
      out.write("        const cart = getCart();\r\n");
      out.write("        const total = cart.reduce((sum, item) => sum + (item.quantity || 1), 0);\r\n");
      out.write("        const cartCount = document.getElementById('cartCount');\r\n");
      out.write("        if (cartCount) cartCount.textContent = total;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Hàm thêm sản phẩm vào giỏ hàng\r\n");
      out.write("    function addToCart(productName, productPrice) {\r\n");
      out.write("        // Thêm vào localStorage\r\n");
      out.write("        let cart = getCart();\r\n");
      out.write("        let found = false;\r\n");
      out.write("        cart = cart.map(item => {\r\n");
      out.write("            if (item.name === productName) {\r\n");
      out.write("                found = true;\r\n");
      out.write("                return { ...item, quantity: (item.quantity || 1) + 1 };\r\n");
      out.write("            }\r\n");
      out.write("            return item;\r\n");
      out.write("        });\r\n");
      out.write("        if (!found) {\r\n");
      out.write("            cart.push({ name: productName, price: productPrice, quantity: 1 });\r\n");
      out.write("        }\r\n");
      out.write("        setCart(cart);\r\n");
      out.write("        updateCartCount();\r\n");
      out.write("\r\n");
      out.write("        // Hiển thị thông báo và liên kết đến cart\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            icon: 'success',\r\n");
      out.write("            title: 'Thành công!',\r\n");
      out.write("            html: `Sản phẩm \"<b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>\" đã được thêm vào giỏ hàng với giá <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productPrice.toLocaleString()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" VNĐ</b>.<br><br>\r\n");
      out.write("                <a href=\"cart\" class=\"swal2-confirm btn btn-primary\" style=\"margin-top:12px;\">Xem giỏ hàng</a>`,\r\n");
      out.write("            showConfirmButton: false,\r\n");
      out.write("            timer: 2200\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Cập nhật số lượng khi tải trang\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        updateCartCount();\r\n");
      out.write("\r\n");
      out.write("        // Hiển thị liên kết user_info nếu đã đăng nhập\r\n");
      out.write("        const userNav = document.getElementById('userNav');\r\n");
      out.write("        const loginData = JSON.parse(localStorage.getItem('rememberLogin') || '{}');\r\n");
      out.write("        const userData = JSON.parse(localStorage.getItem('aishibaUser') || '{}');\r\n");
      out.write("        let isLoggedIn = false;\r\n");
      out.write("        let userName = '';\r\n");
      out.write("\r\n");
      out.write("        // Kiểm tra đăng nhập với tài khoản mặc định hoặc tài khoản đã đăng ký\r\n");
      out.write("        if (\r\n");
      out.write("            (loginData.email === 'user1@example.com' && loginData.password === '12345678') ||\r\n");
      out.write("            (loginData.email === 'admin' && loginData.password === '123456') ||\r\n");
      out.write("            (userData.email && loginData.email === userData.email && loginData.password === userData.password)\r\n");
      out.write("        ) {\r\n");
      out.write("            isLoggedIn = true;\r\n");
      out.write("            userName = userData.name || loginData.email;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (isLoggedIn) {\r\n");
      out.write("            userNav.innerHTML = `\r\n");
      out.write("                <a href=\"user_info\" class=\"nav-item nav-link\" id=\"userInfoNav\">\r\n");
      out.write("                    <i class=\"fa fa-user-circle text-primary mr-2\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName ? userName : 'Tài khoản của tôi'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"login\" class=\"nav-item nav-link\" id=\"logoutNav\">\r\n");
      out.write("                    <i class=\"fa fa-sign-out-alt text-primary mr-2\"></i>Đăng xuất\r\n");
      out.write("                </a>\r\n");
      out.write("            `;\r\n");
      out.write("            // Xử lý đăng xuất\r\n");
      out.write("            document.getElementById('logoutNav').addEventListener('click', function(e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                localStorage.removeItem('rememberLogin');\r\n");
      out.write("                window.location.reload();\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("        function filterProducts() {\r\n");
      out.write("            const selectedCategory = document.getElementById(\"filterCategory\").value;\r\n");
      out.write("            const productCards = document.querySelectorAll(\".product-item\");\r\n");
      out.write("\r\n");
      out.write("            productCards.forEach(card => {\r\n");
      out.write("                const productName = card.querySelector(\"h6\").textContent;\r\n");
      out.write("                if (selectedCategory === \"\" || productName.includes(selectedCategory)) {\r\n");
      out.write("                    card.style.display = \"block\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    card.style.display = \"none\";\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('searchForm').addEventListener('submit', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            const keyword = document.getElementById('searchInput').value.trim();\r\n");
      out.write("            if (keyword) {\r\n");
      out.write("                window.location.href = 'shop?q=' + encodeURIComponent(keyword);\r\n");
      out.write("            } else {\r\n");
      out.write("                window.location.href = 'shop';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    // Thêm sự kiện cho các liên kết danh mục để chuyển sang shop và lọc theo danh mục\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        // Gán sự kiện cho các liên kết danh mục\r\n");
      out.write("        document.querySelectorAll('#navbar-vertical .nav-item.nav-link').forEach(function(link) {\r\n");
      out.write("            link.style.cursor = 'pointer';\r\n");
      out.write("            link.addEventListener('click', function(e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                const category = this.textContent.trim();\r\n");
      out.write("                // Chuyển sang shop với tham số category\r\n");
      out.write("                window.location.href = 'shop?category=' + encodeURIComponent(category);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
