/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-10 03:22:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- Shop Content Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5\">\r\n");
      out.write("        <div class=\"row px-xl-5\">\r\n");
      out.write("            <!-- Shop Sidebar Start -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-12\">\r\n");
      out.write("                <!-- Bộ lọc sản phẩm -->\r\n");
      out.write("                <div class=\"border-bottom mb-4 pb-4\">\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold mb-4\">Lọc theo giá</h5>\r\n");
      out.write("                    <form id=\"priceFilterForm\">\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input price-filter\" id=\"price-all\" data-price=\"all\" checked>\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"price-all\">Tất cả</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input price-filter\" id=\"price-1\" data-price=\"0-100\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"price-1\">0 - 100k</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input price-filter\" id=\"price-2\" data-price=\"100-200\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"price-2\">100k - 200k</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input price-filter\" id=\"price-3\" data-price=\"200-300\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"price-3\">200k - 300k</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Lọc theo thương hiệu -->\r\n");
      out.write("                <div class=\"border-bottom mb-4 pb-4\">\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold mb-4\">Lọc theo thương hiệu</h5>\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"brand-1\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"brand-1\">LEGO</label>\r\n");
      out.write("                            <span class=\"badge border font-weight-normal\">120</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"brand-2\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"brand-2\">Fisher-Price</label>\r\n");
      out.write("                            <span class=\"badge border font-weight-normal\">80</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"brand-3\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"brand-3\">Barbie</label>\r\n");
      out.write("                            <span class=\"badge border font-weight-normal\">60</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"brand-4\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"brand-4\">Hot Wheels</label>\r\n");
      out.write("                            <span class=\"badge border font-weight-normal\">90</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Lọc theo độ tuổi -->\r\n");
      out.write("                <div class=\"border-bottom mb-4 pb-4\">\r\n");
      out.write("                    <h5 class=\"font-weight-semi-bold mb-4\">Lọc theo độ tuổi</h5>\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"age-1\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"age-1\">0 - 2 tuổi</label>\r\n");
      out.write("                            <span class=\"badge border font-weight-normal\">50</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"age-2\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"age-2\">3 - 5 tuổi</label>\r\n");
      out.write("                            <span class=\"badge border font-weight-normal\">120</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"age-3\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"age-3\">6 - 8 tuổi</label>\r\n");
      out.write("                            <span class=\"badge border font-weight-normal\">100</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"custom-control custom-checkbox d-flex align-items-center justify-content-between\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"age-4\">\r\n");
      out.write("                            <label class=\"custom-control-label\" for=\"age-4\">9+ tuổi</label>\r\n");
      out.write("                            <span class=\"badge border font-weight-normal\">80</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Shop Sidebar End -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Shop Product Start -->\r\n");
      out.write("            <div class=\"col-lg-9 col-md-12\">\r\n");
      out.write("                <div class=\"row pb-3\">\r\n");
      out.write("                    <!-- Sản phẩm -->\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"category1\" data-price=\"100000\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-1.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi trẻ em</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>100.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=1\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Tên sản phẩm', 1500000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"category2\" data-price=\"150000\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-2.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi giáo dục</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>150.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=2\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Tên sản phẩm', 1500000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"category3\" data-price=\"200000\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-3.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi mô hình</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>200.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=3\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Tên sản phẩm', 1500000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"category4\" data-price=\"250000\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-9.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi vận động</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>250.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=4\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Tên sản phẩm', 1500000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"category1\" data-price=\"100000\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-5.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi trẻ em</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>100.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=5\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Tên sản phẩm', 1500000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"category2\" data-price=\"150000\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-6.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi giáo dục</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>150.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=6\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Tên sản phẩm', 1500000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"category3\" data-price=\"200000\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-7.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi mô hình</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>200.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=7\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Tên sản phẩm', 1500000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"category4\" data-price=\"250000\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-8.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi vận động</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>250.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=8\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Tên sản phẩm', 1500000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 pb-1\">\r\n");
      out.write("                        <div class=\"card product-item border-0 mb-4\" data-category=\"lego\" data-price=\"150\">\r\n");
      out.write("                            <div class=\"card-header product-img position-relative overflow-hidden bg-transparent border p-0\">\r\n");
      out.write("                                <img class=\"img-fluid w-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/img/product-1.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body border-left border-right text-center p-0 pt-4 pb-3\">\r\n");
      out.write("                                <h6 class=\"text-truncate mb-3\">Đồ chơi LEGO</h6>\r\n");
      out.write("                                <div class=\"d-flex justify-content-center\">\r\n");
      out.write("                                    <h6>150.000đ</h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-footer d-flex justify-content-between bg-light border\">\r\n");
      out.write("                                <a href=\"detail?id=1\" class=\"btn btn-sm text-dark p-0\">\r\n");
      out.write("                                    <i class=\"fas fa-eye text-primary mr-1\"></i>Xem chi tiết\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button class=\"btn btn-sm text-dark p-0\" onclick=\"addToCart('Đồ chơi LEGO', 150000)\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart text-primary mr-1\"></i>Thêm vào giỏ\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 pb-1\">\r\n");
      out.write("                        <nav aria-label=\"Page navigation\">\r\n");
      out.write("                          <ul class=\"pagination justify-content-center mb-3\">\r\n");
      out.write("                            <li class=\"page-item disabled\">\r\n");
      out.write("                              <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("                                <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("                                <span class=\"sr-only\">Previous</span>\r\n");
      out.write("                              </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"page-item active\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                            <li class=\"page-item\">\r\n");
      out.write("                              <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\r\n");
      out.write("                                <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("                                <span class=\"sr-only\">Next</span>\r\n");
      out.write("                              </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Shop Product End -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Shop Content End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("            // Lọc theo danh mục\r\n");
      out.write("            const categoryFilters = document.querySelectorAll(\".category-filter\");\r\n");
      out.write("            categoryFilters.forEach(filter => {\r\n");
      out.write("                filter.addEventListener(\"click\", function (e) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    const category = this.getAttribute(\"data-category\");\r\n");
      out.write("                    filterProductsByCategory(category);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Lọc theo giá\r\n");
      out.write("            const priceFilters = document.querySelectorAll(\".price-filter\");\r\n");
      out.write("            priceFilters.forEach(filter => {\r\n");
      out.write("                filter.addEventListener(\"change\", function () {\r\n");
      out.write("                    const selectedPrices = Array.from(priceFilters)\r\n");
      out.write("                        .filter(input => input.checked)\r\n");
      out.write("                        .map(input => input.getAttribute(\"data-price\"));\r\n");
      out.write("                    filterProductsByPrice(selectedPrices);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Hàm lọc sản phẩm theo danh mục\r\n");
      out.write("            function filterProductsByCategory(category) {\r\n");
      out.write("                const products = document.querySelectorAll(\".product-item\");\r\n");
      out.write("                products.forEach(product => {\r\n");
      out.write("                    const productCategory = product.getAttribute(\"data-category\");\r\n");
      out.write("                    if (category === \"all\" || productCategory === category) {\r\n");
      out.write("                        product.style.display = \"block\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                        product.style.display = \"none\";\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Hàm lọc sản phẩm theo giá\r\n");
      out.write("            function filterProductsByPrice(selectedPrices) {\r\n");
      out.write("                const products = document.querySelectorAll(\".product-item\");\r\n");
      out.write("                products.forEach(product => {\r\n");
      out.write("                    const productPrice = parseInt(product.getAttribute(\"data-price\"));\r\n");
      out.write("                    let showProduct = false;\r\n");
      out.write("\r\n");
      out.write("                    selectedPrices.forEach(priceRange => {\r\n");
      out.write("                        if (priceRange === \"all\") {\r\n");
      out.write("                            showProduct = true;\r\n");
      out.write("                        } else {\r\n");
      out.write("                            const [min, max] = priceRange.split(\"-\").map(Number);\r\n");
      out.write("                            if (productPrice >= min && productPrice <= max) {\r\n");
      out.write("                                showProduct = true;\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    product.style.display = showProduct ? \"block\" : \"none\";\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // Lấy từ khóa tìm kiếm từ URL (nếu có)\r\n");
      out.write("            const params = new URLSearchParams(window.location.search);\r\n");
      out.write("            const keyword = (params.get('q') || '').toLowerCase();\r\n");
      out.write("\r\n");
      out.write("            const searchInput = document.getElementById('searchInput');\r\n");
      out.write("            const clearBtn = document.getElementById('clearSearch');\r\n");
      out.write("\r\n");
      out.write("            // Hiện nút x khi có từ khóa\r\n");
      out.write("            function toggleClearBtn() {\r\n");
      out.write("                if (searchInput.value.trim() !== '') {\r\n");
      out.write("                    clearBtn.style.display = '';\r\n");
      out.write("                } else {\r\n");
      out.write("                    clearBtn.style.display = 'none';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Hàm hiển thị lại tất cả sản phẩm\r\n");
      out.write("            function showAllProducts() {\r\n");
      out.write("                document.querySelectorAll('.product-item').forEach(card => {\r\n");
      out.write("                    card.style.display = 'block';\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Sự kiện cho nút x\r\n");
      out.write("            clearBtn.addEventListener('click', function() {\r\n");
      out.write("                searchInput.value = '';\r\n");
      out.write("                toggleClearBtn();\r\n");
      out.write("                showAllProducts();\r\n");
      out.write("                const info = document.getElementById('searchResultInfo');\r\n");
      out.write("                if (info) info.innerHTML = '';\r\n");
      out.write("                // Xóa tham số q trên URL nếu có\r\n");
      out.write("                if (window.history.replaceState) {\r\n");
      out.write("                    const url = new URL(window.location);\r\n");
      out.write("                    url.searchParams.delete('q');\r\n");
      out.write("                    window.history.replaceState({}, '', url.pathname);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Sự kiện input để hiện/tắt nút x\r\n");
      out.write("            searchInput.addEventListener('input', toggleClearBtn);\r\n");
      out.write("\r\n");
      out.write("            // Khi vào trang, kiểm tra có từ khóa không để hiện nút x\r\n");
      out.write("            toggleClearBtn();\r\n");
      out.write("\r\n");
      out.write("            // Hàm lọc sản phẩm theo tên\r\n");
      out.write("            function filterByKeyword(kw) {\r\n");
      out.write("                const keyword = removeVietnameseTones(kw.toLowerCase());\r\n");
      out.write("                let count = 0;\r\n");
      out.write("                const productCards = Array.from(document.querySelectorAll('.product-item'));\r\n");
      out.write("                const matched = [];\r\n");
      out.write("                const unmatched = [];\r\n");
      out.write("\r\n");
      out.write("                productCards.forEach(card => {\r\n");
      out.write("                    const name = card.querySelector('h6').textContent;\r\n");
      out.write("                    const nameNormalized = removeVietnameseTones(name.toLowerCase());\r\n");
      out.write("                    if (nameNormalized.includes(keyword)) {\r\n");
      out.write("                        card.style.display = 'block';\r\n");
      out.write("                        matched.push(card);\r\n");
      out.write("                        count++;\r\n");
      out.write("                    } else {\r\n");
      out.write("                        card.style.display = 'none';\r\n");
      out.write("                        unmatched.push(card);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Sắp xếp lại DOM: đưa sản phẩm khớp lên đầu\r\n");
      out.write("                if (matched.length > 0) {\r\n");
      out.write("                    const row = matched[0].closest('.row.pb-3');\r\n");
      out.write("                    matched.forEach(card => row.appendChild(card.closest('.col-lg-4, .col-md-6, .col-sm-12, .pb-1')));\r\n");
      out.write("                    unmatched.forEach(card => row.appendChild(card.closest('.col-lg-4, .col-md-6, .col-sm-12, .pb-1')));\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // Hiển thị thông báo kết quả\r\n");
      out.write("                const info = document.getElementById('searchResultInfo');\r\n");
      out.write("                if (kw && info) {\r\n");
      out.write("                    if (count > 0) {\r\n");
      out.write("                        info.innerHTML = `Tìm thấy <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b> sản phẩm cho từ khóa: <b>\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kw}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"</b>`;\r\n");
      out.write("                    } else {\r\n");
      out.write("                        info.innerHTML = `Không tìm thấy sản phẩm nào cho từ khóa: <b>\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kw}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"</b>`;\r\n");
      out.write("                    }\r\n");
      out.write("                } else if (info) {\r\n");
      out.write("                    info.innerHTML = '';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Nếu có từ khóa trên URL thì lọc ngay khi vào trang\r\n");
      out.write("            if (keyword) {\r\n");
      out.write("                filterByKeyword(keyword);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Bắt sự kiện submit form tìm kiếm\r\n");
      out.write("            const searchForm = searchInput?.closest('form');\r\n");
      out.write("            if (searchForm) {\r\n");
      out.write("                searchForm.addEventListener('submit', function(e) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    const kw = searchInput.value.trim().toLowerCase();\r\n");
      out.write("                    filterByKeyword(kw);\r\n");
      out.write("                    // Nếu muốn thay đổi URL khi tìm kiếm mới:\r\n");
      out.write("                    // window.history.replaceState({}, '', '?q=' + encodeURIComponent(kw));\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Hàm loại bỏ dấu tiếng Việt\r\n");
      out.write("        function removeVietnameseTones(str) {\r\n");
      out.write("            return str.normalize('NFD').replace(/[\\u0300-\\u036f]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D');\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- Thêm đoạn script này ngay trước </body> để đổi nút đăng nhập thành tên tài khoản và Đăng xuất khi đã đăng nhập -->\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    // Đổi màu các thành phần header cho đồng bộ\r\n");
      out.write("    document.querySelectorAll('.bg-primary').forEach(e => e.style.background = '#D19C97');\r\n");
      out.write("    document.querySelectorAll('.text-primary').forEach(e => e.style.color = '#D19C97');\r\n");
      out.write("    document.querySelectorAll('.badge-primary').forEach(e => e.style.background = '#D19C97');\r\n");
      out.write("    document.querySelectorAll('.nav-link.active').forEach(e => e.style.color = '#D19C97');\r\n");
      out.write("\r\n");
      out.write("    // Hiển thị liên kết user_info nếu đã đăng nhập\r\n");
      out.write("    const userNav = document.getElementById('userNav');\r\n");
      out.write("    const loginData = JSON.parse(localStorage.getItem('rememberLogin') || '{}');\r\n");
      out.write("    const userData = JSON.parse(localStorage.getItem('aishibaUser') || '{}');\r\n");
      out.write("    let isLoggedIn = false;\r\n");
      out.write("    let userName = '';\r\n");
      out.write("\r\n");
      out.write("    // Kiểm tra đăng nhập với tài khoản mặc định hoặc tài khoản đã đăng ký\r\n");
      out.write("    if (\r\n");
      out.write("        (loginData.email === 'user1@example.com' && loginData.password === '12345678') ||\r\n");
      out.write("        (loginData.email === 'admin' && loginData.password === '123456') ||\r\n");
      out.write("        (userData.email && loginData.email === userData.email && loginData.password === userData.password)\r\n");
      out.write("    ) {\r\n");
      out.write("        isLoggedIn = true;\r\n");
      out.write("        userName = userData.name || loginData.email;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (isLoggedIn && userNav) {\r\n");
      out.write("        userNav.innerHTML = `\r\n");
      out.write("            <a href=\"user_info\" class=\"nav-item nav-link\" style=\"color:#D19C97;\">\r\n");
      out.write("                <i class=\"fa fa-user text-primary mr-2\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName ? userName : 'Tài khoản của tôi'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"nav-item nav-link\" id=\"logoutNav\" style=\"color:#D19C97;\">\r\n");
      out.write("                <i class=\"fa fa-sign-out-alt text-primary mr-2\"></i>Đăng xuất\r\n");
      out.write("            </a>\r\n");
      out.write("        `;\r\n");
      out.write("        document.getElementById('logoutNav').addEventListener('click', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            localStorage.removeItem('rememberLogin');\r\n");
      out.write("            window.location.reload();\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("// Hàm lấy giỏ hàng từ localStorage\r\n");
      out.write("function getCart() {\r\n");
      out.write("    return JSON.parse(localStorage.getItem('cart') || '[]');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Hàm lưu giỏ hàng vào localStorage\r\n");
      out.write("function setCart(cart) {\r\n");
      out.write("    localStorage.setItem('cart', JSON.stringify(cart));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Hàm cập nhật số lượng sản phẩm trên icon giỏ hàng\r\n");
      out.write("function updateCartCount() {\r\n");
      out.write("    const cart = getCart();\r\n");
      out.write("    const total = cart.reduce((sum, item) => sum + (item.quantity || 1), 0);\r\n");
      out.write("    const cartCount = document.getElementById('cartCount');\r\n");
      out.write("    if (cartCount) cartCount.textContent = total;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Hàm thêm sản phẩm vào giỏ hàng\r\n");
      out.write("function addToCart(productName, productPrice) {\r\n");
      out.write("    let cart = getCart();\r\n");
      out.write("    let found = false;\r\n");
      out.write("    cart = cart.map(item => {\r\n");
      out.write("        if (item.name === productName) {\r\n");
      out.write("            found = true;\r\n");
      out.write("            return { ...item, quantity: (item.quantity || 1) + 1 };\r\n");
      out.write("        }\r\n");
      out.write("        return item;\r\n");
      out.write("    });\r\n");
      out.write("    if (!found) {\r\n");
      out.write("        cart.push({ name: productName, price: productPrice, quantity: 1 });\r\n");
      out.write("    }\r\n");
      out.write("    setCart(cart);\r\n");
      out.write("    updateCartCount();\r\n");
      out.write("\r\n");
      out.write("    // Hiển thị modal thông báo thành công\r\n");
      out.write("    showSuccessModal(productName, productPrice);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Hàm hiển thị modal thông báo thành công\r\n");
      out.write("function showSuccessModal(productName, price) {\r\n");
      out.write("    let oldModal = document.getElementById('successModal');\r\n");
      out.write("    if (oldModal) oldModal.remove();\r\n");
      out.write("\r\n");
      out.write("    let modal = document.createElement('div');\r\n");
      out.write("    modal.id = 'successModal';\r\n");
      out.write("    modal.style.position = 'fixed';\r\n");
      out.write("    modal.style.top = '0';\r\n");
      out.write("    modal.style.left = '0';\r\n");
      out.write("    modal.style.width = '100vw';\r\n");
      out.write("    modal.style.height = '100vh';\r\n");
      out.write("    modal.style.background = 'rgba(0,0,0,0.35)';\r\n");
      out.write("    modal.style.display = 'flex';\r\n");
      out.write("    modal.style.alignItems = 'center';\r\n");
      out.write("    modal.style.justifyContent = 'center';\r\n");
      out.write("    modal.style.zIndex = 10000;\r\n");
      out.write("\r\n");
      out.write("    modal.innerHTML = `\r\n");
      out.write("        <div style=\"background:#fff; border-radius:12px; max-width:480px; width:90%; padding:36px 32px 28px 32px; box-shadow:0 8px 32px rgba(0,0,0,0.18); text-align:center; position:relative;\">\r\n");
      out.write("            <div style=\"margin-bottom:18px;\">\r\n");
      out.write("                <svg width=\"80\" height=\"80\" viewBox=\"0 0 80 80\">\r\n");
      out.write("                    <circle cx=\"40\" cy=\"40\" r=\"38\" fill=\"none\" stroke=\"#d4f5dd\" stroke-width=\"4\"/>\r\n");
      out.write("                    <polyline points=\"25,43 37,55 56,30\" fill=\"none\" stroke=\"#6fcf97\" stroke-width=\"5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h2 style=\"font-weight:700; color:#444; margin-bottom:12px;\">Thành công!</h2>\r\n");
      out.write("            <div style=\"color:#555; font-size:1.1rem; margin-bottom:24px;\">\r\n");
      out.write("                Sản phẩm <b>\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"</b> đã được thêm vào giỏ hàng với giá <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price.toLocaleString()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" VNĐ</b>.\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"cart\" id=\"successModalOk\" style=\"display:inline-block;padding:8px 32px; font-size:1.1rem; border:none; border-radius:8px; background:#7b7be6; color:#fff; font-weight:600; box-shadow:0 2px 8px rgba(123,123,230,0.08); cursor:pointer; text-decoration:none;\">Xem giỏ hàng</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    `;\r\n");
      out.write("    document.body.appendChild(modal);\r\n");
      out.write("\r\n");
      out.write("    // Đóng modal khi click ra ngoài\r\n");
      out.write("    modal.addEventListener('click', function(e) {\r\n");
      out.write("        if (e.target === modal) modal.remove();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Cập nhật số lượng khi tải trang\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    updateCartCount();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("// filepath: d:\\Git\\ToyshopServlet\\Enduser\\eshopper-1.0.0\\shop\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("    // Liên kết danh mục sang shop?category=... và lọc khi vào trang\r\n");
      out.write("    document.querySelectorAll('#navbar-vertical .nav-item.nav-link').forEach(function(link) {\r\n");
      out.write("        link.style.cursor = 'pointer';\r\n");
      out.write("        link.addEventListener('click', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            const category = this.textContent.trim();\r\n");
      out.write("            window.location.href = 'shop?category=' + encodeURIComponent(category);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Lọc sản phẩm theo danh mục từ URL\r\n");
      out.write("    const params = new URLSearchParams(window.location.search);\r\n");
      out.write("    const categoryParam = params.get('category');\r\n");
      out.write("    if (categoryParam) {\r\n");
      out.write("        // Ẩn tất cả sản phẩm, chỉ hiện sản phẩm đúng danh mục\r\n");
      out.write("        document.querySelectorAll('.product-item').forEach(function(card) {\r\n");
      out.write("            const name = card.querySelector('h6').textContent.trim();\r\n");
      out.write("            if (name === categoryParam) {\r\n");
      out.write("                card.closest('.col-lg-4, .col-md-6, .col-sm-12, .pb-1').style.display = 'block';\r\n");
      out.write("            } else {\r\n");
      out.write("                card.closest('.col-lg-4, .col-md-6, .col-sm-12, .pb-1').style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        // Hiển thị thông báo kết quả lọc\r\n");
      out.write("        let info = document.getElementById('searchResultInfo');\r\n");
      out.write("        if (!info) {\r\n");
      out.write("            info = document.createElement('div');\r\n");
      out.write("            info.id = 'searchResultInfo';\r\n");
      out.write("            info.className = 'mb-3';\r\n");
      out.write("            const row = document.querySelector('.row.pb-3');\r\n");
      out.write("            if (row) row.parentNode.insertBefore(info, row);\r\n");
      out.write("        }\r\n");
      out.write("        // Đếm số sản phẩm hiển thị\r\n");
      out.write("        const count = Array.from(document.querySelectorAll('.product-item')).filter(card =>\r\n");
      out.write("            card.closest('.col-lg-4, .col-md-6, .col-sm-12, .pb-1').style.display !== 'none'\r\n");
      out.write("        ).length;\r\n");
      out.write("        info.innerHTML = `Tìm thấy <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b> sản phẩm cho danh mục: <b>\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryParam}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"</b>`;\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
